using System;
using System.Collections.Generic;
using CycloneDDS.Schema;
using Hrot.NED.Common;

namespace Hrot.NED.Messages
{
    // ===================================================================================
    // MAP INTERACTION: USER INPUT EVENTS
    // ===================================================================================
    // Events generated by the IG when the user interacts with the map hardware (Mouse/Touch).
    // All events are scoped to a specific MapId (Instance).
    // ===================================================================================

    public enum EEntitySymbolPart
    {
        ESP_BODY,
        ESP_ICON,
        ESP_LABEL
    }

    // Describes an object under the mouse cursor.
    [DdsStruct]
    [DdsIdlFile("hrot-map-msgs")]
    public partial struct MapObjectRef
    {
        // The ID of the entity.
        public int EntityId;

        // The type of the entity (helper to avoid looking up Master).
        public int TkbType;

        // DIS entity type info.
        public ulong DisType;

        // Which part was clicked? (Icon, Label, or the 3D Body).
        public EEntitySymbolPart VisualPart;
    }

    // Event sent when the user clicks on the map.
    // Includes a "Hit Stack" of all objects under the cursor (for disambiguation).
    [DdsTopic("MapClickEvent")]
    [DdsIdlFile("hrot-map-msgs")]
    [DdsQos(Reliability = DdsReliability.Reliable, Durability = DdsDurability.Volatile, HistoryKind = DdsHistoryKind.KeepAll)]
    public partial struct MapClickEvent
    {
        // The specific IG Instance where the click happened.
        public int MapId;

        // World coordinates of the click.
        public GeoPoint Position;

        // List of objects under the cursor, ordered Top-to-Bottom (Z-order).
        [DdsManaged]
        public List<MapObjectRef> HitStack;

        // The Context ID active at the time of the click.
        // Allows ExCon to route this click to the correct Tool logic.
        public Guid InteractionContextId;
    }

    public enum DragState
    {
        DRAG_START,
        DRAG_UPDATE,
        DRAG_END,
        DRAG_CANCEL
    }

    // Event sent during a drag-and-drop operation.
    // Used for "Local Prediction": IG moves the object visually, sends updates to ExCon.
    /*
    **Drag Modes** (configured in tool settings):

    | Mode                    | Behavior                                         | Use Case                        |
    | ----------------------- | ------------------------------------------------ | ------------------------------- |
    | **Local Preview**       | Only local visualization moves; commit on drop   | Default safe mode               |
    | **Backbone on Drop**    | IG emits DragEnd; ExCon commits to backbone        | Standard entity move            |
    | **Continuous Backbone** | Intermediate updates published (explicit opt-in) | Real-time collaborative editing |
    */
    [DdsTopic("DragEvent")]
    [DdsIdlFile("hrot-map-msgs")]
    [DdsQos(Reliability = DdsReliability.Reliable, Durability = DdsDurability.Volatile, HistoryKind = DdsHistoryKind.KeepAll)]
    public partial struct DragEvent
    {
        // The specific IG Instance.
        public int MapId;

        // Current phase: START (Picked up), UPDATE (Moving), END (Dropped), CANCEL (Esc).
        public DragState State;

        // The Entity being dragged.
        public int EntityId;

        // Current world coordinates of the cursor/object.
        public GeoPoint CurrentPosition;

        // The Context ID associated with this drag operation.
        public Guid InteractionContextId;
    }

    // Event sent when the user modifies the selection set (e.g., Box Select, Ctrl+Click).
    // The IG is authoritative for the selection state.
    [DdsTopic("SelectionChangedEvent")]
    [DdsIdlFile("hrot-map-msgs")]
    public partial struct SelectionChangedEvent
    {
        // The specific IG Instance.
        public int MapId;
        
        // The complete list of currently selected Entity IDs.
        // Replaces any previous selection state.
        [DdsManaged]
        public List<int> SelectedEntityIds;
    }

    // 4. Commands (ExCon -> IG)
    public enum CommandType
    {
        CMD_SET_VIEW,
        CMD_SET_SELECTION,
        CMD_START_EDITING,
        /// <summary>
        /// Activate the entity-placement (creation) tool on a specific IG window.
        /// Args JSON: { "contextId": "&lt;guid&gt;", "entityType": 8001, "affiliation": "FORCE_FRIENDLY" }
        /// </summary>
        CMD_PLACE_ENTITY,
        /// <summary>
        /// Activate the polygonal area-authoring tool on a specific IG window.
        /// Args JSON: { "contextId": "&lt;guid&gt;", "styleOverrideJson": "..." }
        /// </summary>
        CMD_START_AUTHORING,
        /// <summary>
        /// Activate a one-shot location-pick mode on a specific IG window.
        /// The IG shows a crosshair cursor; the operator's next left-click publishes
        /// a <see cref="MapClickEvent"/> with the world-space GeoPosition and the
        /// correlated context ID so the ExCon can resolve a pending location pick.
        /// Args JSON: { "contextId": "&lt;guid&gt;" }
        /// </summary>
        CMD_PICK_LOCATION,
        /// <summary>
        /// Activate an entity-picker tool on a specific IG window.
        /// The IG renders a target crosshair that turns red over pickable entities;
        /// clicking a valid entity publishes a <see cref="MapClickEvent"/> with the
        /// entity in <c>HitStack</c> and the correlated context ID.
        /// Args JSON: { "contextId": "&lt;guid&gt;", "filters": ["road_graphs", "tactical_graphics"] }
        /// </summary>
        CMD_PICK_ENTITY,        /// <summary>
        /// Activates route-authoring on the IG and automatically assigns the
        /// resulting route as a personal navigation mission for the target entity.
        /// Args JSON: { "contextId": "&lt;guid&gt;", "entityId": 12345 }
        /// </summary>
        CMD_DRAW_PERSONAL_ROUTE,    }

    // Imperative commands sent from ExCon to a specific IG Instance.
    // Used to force a specific behavior (e.g., "Pan Camera Here", "Enter Edit Mode").
    [DdsTopic("MapCommandRequest")]
    [DdsIdlFile("hrot-map-msgs")]
    [DdsQos(Reliability = DdsReliability.Reliable, Durability = DdsDurability.Volatile, HistoryKind = DdsHistoryKind.KeepAll)]
    [DdsManaged]
    public partial struct MapCommandRequest
    {
        // Unique ID for this request.
        // Used to match with CommandStatus / Ack.
        public Guid RequestId;

        // Target IG Instance.
        public int MapId;

        // Type of command (View, Selection, Editing).
        public CommandType Type;

        // Arguments for the command in JSON format.
        // e.g., { "lat": 45.0, "lon": 12.0, "zoom": 1000 }
        public string CommandArgsJson;
    }

    // ===================================================================================
    // MAP INTERACTION: CONTEXT MENUS (PUSH MODEL)
    // ===================================================================================
    // Principle: Zero-Latency UI.
    // 1. User Selects Entity -> ExCon calculates menu -> ExCon Pushes 'ContextActionsUpdate'.
    // 2. IG caches update.
    // 3. User Right-Clicks -> IG opens menu from cache instantly.
    // 4. Fallback: If cache miss, IG sends 'ContextMenuRequest'.
    // 5. Execution: User clicks item -> IG sends 'ContextActionInvoked'.
    // ===================================================================================

    // Event sent by the IG when the user clicks a specific item in the context menu.
    // Direction: IG -> ExCon
    [DdsTopic("ContextActionInvoked")]
    [DdsIdlFile("hrot-map-msgs")]
    [DdsQos(Reliability = DdsReliability.Reliable, Durability = DdsDurability.Volatile, HistoryKind = DdsHistoryKind.KeepAll)]
    public partial struct ContextActionInvoked
    {
        // Source IG Instance.
        public int MapId;

        // The ID of the action chosen (defined in the JSON menu).
        public int ActionId;

        // The ID of the specific entity on which the menu was opened.
        // Necessary for resolving ambiguity in multi-selections.
        public int ContextEntityId;

        // The Context ID active when the menu was opened.
        public Guid ContextId;
    }

    // Fallback request sent by the IG when the user right-clicks an entity
    // that does NOT have a cached menu definition available.
    // Direction: IG -> ExCon
    [DdsTopic("ContextMenuRequest")]
    [DdsIdlFile("hrot-map-msgs")]
    [DdsQos(Reliability = DdsReliability.Reliable, Durability = DdsDurability.Volatile, HistoryKind = DdsHistoryKind.KeepAll)]
    public partial struct ContextMenuRequest
    {
        // Unique ID for this request. Must be echoed in the response.
        public Guid RequestId;

        // Source IG Instance (where the user clicked).
        public int MapId;

        // The list of entities currently selected/clicked.
        // ExCon uses this to generate the appropriate menu options.
        [DdsManaged]
        public List<int> ForSelection;
    }

    // ===================================================================================
    // MAP COMMAND ACK (IG -> ExCon)
    // ===================================================================================
    // Response to a MapCommandRequest.
    // One request can generate multiple responses. For example,
    //   a map placement tool can be configured to create one entity every left click
    //   and finish on right click or ESC key.
    // ===================================================================================

    // Response to the MapCommandRequest.
    // One request can generate multiple responses. For example,
    //   a map placement tool can be configured to create one entity every left click
    //   and finish on right click or ESC key.
    [DdsTopic("MapCommandAck")]
    [DdsIdlFile("hrot-map-msgs")]
    [DdsQos(Reliability = DdsReliability.Reliable, Durability = DdsDurability.Volatile, HistoryKind = DdsHistoryKind.KeepAll)]
    [DdsManaged]
    public partial struct MapCommandAck
    {
        // Correlation id with the original MapCommandRequest.
        public Guid RequestId;

        // 0 = request finished (request can be closed)
        // 1 = intermediate result (request not closed yet, other acks to come)
        // 2 = cancelled (tool was cancelled without completing any work)
        // other values reserved for various error codes
        public long StatusCode;

        // Carries request-type specific extra data, for example the id of entity created,
        // or a list of ids. Or for example the 'tool finalized' flag.
        // For each request type the app should define a data structure describing the expected
        // content, serving as a schema definition (including what fields are optional).
        // Example for CMD_PLACE_ENTITY: { "entityId": 42 }
        public string DataJson;
    }

    // Proactive update from ExCon containing the context menu definition for a specific selection.
    // Direction: ExCon -> IG
    [DdsTopic("ContextActionsUpdate")]
    [DdsIdlFile("hrot-map-msgs")]
    [DdsQos(Reliability = DdsReliability.Reliable, Durability = DdsDurability.Volatile, HistoryKind = DdsHistoryKind.KeepAll)]
    [DdsManaged]
    public partial struct ContextActionsUpdate
    {
        // Target Map Group (Role).
        // Menus are business logic, so they apply to the Role (e.g. "Instructor"), 
        // not just one screen.
        public int MapGroupId;

        // Validation list: Which selected entities does this menu apply to?
        // The IG checks this against its current selection. If the user's selection 
        // has changed since this message was generated, the IG discards this update.
        [DdsManaged]
        public List<int> ForSelection;

        // Menu structure as JSON.
        // Supports nested menus, icons, shortcuts, and enable/disable states.
        // Menu structure as JSON (flexible, nestable)
        // See "Menu JSON Schema" below
            /*
                [
                {
                    "id": 100,
                    "label": "Move Here",
                    "icon": "move_cursor",
                    "shortcut": "M",
                    "enabled": true
                },
                { "type": "separator" },
                {
                    "label": "Logistics",
                    "icon": "gear",
                    "children": [
                    {
                        "id": 201,
                        "label": "Resupply",
                        "enabled": false,
                        "tooltip": "Cannot resupply: Unit is moving"
                    },
                    { "id": 202, "label": "Repair" }
                    ]
                }
                ]
            */
        public string MenuDefinitionJson;
    }
}
