using System.Text;
using Hrot.Blueprints.Core.Assets;
using Hrot.Blueprints.Core.Compiler.Ir;
using AssetDispatch = Hrot.Blueprints.Core.Assets.BlueprintDispatchKind;

namespace Hrot.Blueprints.Core.Compiler.Emit;

internal sealed class CSharpEmitter
{
    private readonly StringBuilder _sb = new();
    private readonly DebugMapBuilder _debugMap;
    private readonly EmissionContext _ctx;
    private int _indent;
    private int _currentLine = 1;

    public CSharpEmitter(EmissionContext ctx)
    {
        _ctx = ctx;
        _debugMap = new DebugMapBuilder(ctx.Asset.AssetId, ctx.Asset.BlueprintId, ctx.Asset.StructureHash);
    }

    public EmissionContext Ctx => _ctx;
    public int CurrentLine => _currentLine;

    public void Write(string text)
    {
        _sb.Append(text);
        foreach (char c in text)
            if (c == '\n') _currentLine++;
    }

    public void WriteLine(string line = "")
    {
        for (int i = 0; i < _indent; i++) _sb.Append("    ");
        _sb.Append(line);
        _sb.Append('\n');
        _currentLine++;
    }

    public void Indent() => _indent++;
    public void Outdent() => _indent = Math.Max(0, _indent - 1);

    public void EmitNodeStart(IrDebugAnnotation? debug)
    {
        if (debug?.NodeId is null) return;
        _debugMap.RecordNodeStart(debug.NodeId.Value, debug.GraphId, _currentLine,
            debug.NodeKind, debug.DisplayName);
    }

    public void EmitNodeEnd(IrDebugAnnotation? debug)
    {
        if (debug?.NodeId is null) return;
        _debugMap.RecordNodeEnd(debug.NodeId.Value, _currentLine);
    }

    public (string Source, DebugMap DebugMap) Emit(IrAsset asset)
    {
        _debugMap.SetAssetName(asset.Name);
        _debugMap.SetGeneratedSourcePath($"generated/{asset.SanitizedName}_{asset.BlueprintId:X8}.cs");

        foreach (var graph in asset.Graphs)
        {
            _debugMap.AddGraph(new DebugGraphInfo(graph.Id, graph.Name, graph.Kind.ToString()));
            foreach (var field in graph.Inputs)
                _debugMap.AddPin(new DebugPinInfo(field.Id, graph.Id, field.Name, "Input", "Data",
                    StatementEmitter.TypeRefToCSharp(field.Type), field.Name));
            foreach (var field in graph.Outputs)
                _debugMap.AddPin(new DebugPinInfo(field.Id, graph.Id, field.Name, "Output", "Data",
                    StatementEmitter.TypeRefToCSharp(field.Type), field.Name));
        }

        if (asset.Dispatch == AssetDispatch.Instance)
        {
            foreach (var field in asset.Variables)
            {
                _debugMap.AddPin(new DebugPinInfo(field.Id, Guid.Empty, field.Name, "Output", "Variable",
                    StatementEmitter.TypeRefToCSharp(field.Type), $"s.{field.Name}"));
                _debugMap.AddStateLayoutField(new StateLayoutField(
                    field.Name, field.Type.FullName, field.Offset, field.Size));
            }
        }

        EmitFileHeader(asset);
        EmitUsings();
        WriteLine();

        switch (asset.Dispatch)
        {
            case AssetDispatch.Library:
                LibraryEmitter.EmitClass(this, asset);
                break;
            case AssetDispatch.AiPrimitive:
                AiPrimitiveEmitter.EmitClass(this, asset);
                break;
            case AssetDispatch.Instance:
                InstanceEmitter.EmitClass(this, asset);
                break;
            default:
                throw new NotSupportedException($"Unknown dispatch kind: {asset.Dispatch}");
        }

        WriteLine();
        EmitRegistrarClass(asset);
        return (_sb.ToString(), _debugMap.Build());
    }

    private void EmitFileHeader(IrAsset asset)
    {
        WriteLine("// <auto-generated />");
        WriteLine($"// Asset: {asset.Name} ({asset.AssetId})");
        WriteLine($"// BlueprintId: 0x{asset.BlueprintId:X8}");
        WriteLine($"// StructureHash: 0x{asset.StructureHash:X16}");
        WriteLine();
    }

    private void EmitUsings()
    {
        WriteLine("using System;");
        WriteLine("using System.Runtime.CompilerServices;");
        WriteLine("using System.Runtime.InteropServices;");
        WriteLine("using System.Numerics;");
        WriteLine("using Fdp.Core;");
        WriteLine("using Fdp.Interfaces;");
        WriteLine("using Fdp.ModuleHost.Abstractions;");
        WriteLine("using Fdp.Toolkit.Blueprints;");
    }

    private void EmitRegistrarClass(IrAsset asset)
    {
        var className = $"{asset.SanitizedName}_{asset.BlueprintId:X8}_Bp";
        var registrarName = $"BlueprintRegistrar_{asset.SanitizedName}_{asset.BlueprintId:X8}_Bp";

        bool needsBehReg = asset.Hostings.Any(h =>
            h == AiPrimitiveHosting.BTreeAction || h == AiPrimitiveHosting.BTreeCondition);

        bool hasConditionMet = asset.Dispatch == AssetDispatch.Instance &&
            asset.Graphs
                .SelectMany(g => g.Blocks)
                .SelectMany(b => b.Statements)
                .Any(s => s.Operation is IrOp_WhenConditionMetCheck);

        WriteLine("[global::Fdp.Toolkit.Blueprints.Attributes.BlueprintRegistrar]");
        WriteLine($"public static class {registrarName}");
        WriteLine("{");
        Indent();

        var paramParts = new System.Collections.Generic.List<string>
            { "global::Fdp.Toolkit.Blueprints.BlueprintRegistryStaging staging" };
        if (needsBehReg)
            paramParts.Add("global::Fdp.Toolkit.Behavior.BehaviorRegistry behReg");
        if (hasConditionMet)
        {
            paramParts.Add("global::Fdp.Toolkit.ReplayBrowser.Search.IPredicateCompiler predicateCompiler");
            paramParts.Add("global::Hrot.Blueprints.Core.Compiler.ISearchPredicateRegistry dtoRegistry");
        }
        var paramSig = string.Join(", ", paramParts);

        WriteLine($"public static unsafe void Register({paramSig})");
        WriteLine("{");
        Indent();

        switch (asset.Dispatch)
        {
            case AssetDispatch.Library:
                EmitLibraryRegistration(className, asset);
                break;
            case AssetDispatch.AiPrimitive:
                EmitAiPrimitiveRegistration(className, asset, needsBehReg);
                break;
            case AssetDispatch.Instance:
                if (hasConditionMet)
                    WriteLine($"{className}.InitializePredicates(predicateCompiler, dtoRegistry);");
                EmitInstanceRegistration(className, asset);
                break;
        }

        Outdent();
        WriteLine("}");
        Outdent();
        WriteLine("}");
    }

    private void EmitLibraryRegistration(string className, IrAsset asset)
    {
        WriteLine($"staging.Add({className}.BlueprintId, new global::Fdp.Toolkit.Blueprints.BlueprintDefinition");
        WriteLine("{");
        Indent();
        WriteLine($"Name = \"{asset.Name}\",");
        WriteLine("Kind = global::Fdp.Toolkit.Blueprints.BlueprintDispatchKind.Library,");
        WriteLine($"StructureHash = {asset.StructureHash}UL,");
        WriteLine("StateSize = 0,");
        Outdent();
        WriteLine("});");
    }

    private void EmitAiPrimitiveRegistration(string className, IrAsset asset, bool needsBehReg)
    {
        WriteLine($"staging.Add({className}.BlueprintId, new global::Fdp.Toolkit.Blueprints.BlueprintDefinition");
        WriteLine("{");
        Indent();
        WriteLine($"Name = \"{asset.Name}\",");
        WriteLine("Kind = global::Fdp.Toolkit.Blueprints.BlueprintDispatchKind.AiPrimitive,");
        WriteLine($"StructureHash = {className}.StructureHash,");
        WriteLine("StateSize = 0,");
        Outdent();
        WriteLine("});");

        // Register BTree thunks with BehaviorRegistry (Patch C1 / TASK-CP-004)
        if (asset.Hostings.Contains(AiPrimitiveHosting.BTreeAction))
            WriteLine($"behReg.RegisterAction({className}.BlueprintId, \"{asset.Name}\", {className}.BTreeTick);");
        if (asset.Hostings.Contains(AiPrimitiveHosting.BTreeCondition))
            WriteLine($"behReg.RegisterCondition({className}.BlueprintId, \"{asset.Name}\", {className}.BTreeEvaluate);");

        // Register HSM thunks via static calls (HsmActionDispatcher is a static unsafe class,
        // not injectable; Patch C1). The unmanaged function pointers are cast to IntPtr.
        if (asset.Hostings.Contains(AiPrimitiveHosting.HsmAction))
            WriteLine($"global::Fhsm.Kernel.HsmActionDispatcher.RegisterAction(unchecked((ushort){className}.BlueprintId), (global::System.IntPtr)(delegate* <void*, void*, global::Fhsm.Kernel.Data.HsmCommandWriter*, void>)&{className}.HsmActivity);");
        if (asset.Hostings.Contains(AiPrimitiveHosting.HsmGuard))
            WriteLine($"global::Fhsm.Kernel.HsmActionDispatcher.RegisterGuard(unchecked((ushort){className}.BlueprintId), (global::System.IntPtr)(delegate* <void*, void*, ushort, bool>)&{className}.HsmGuard);");
    }

    private void EmitInstanceRegistration(string className, IrAsset asset)
    {
        var eventHandlers = asset.Graphs
            .Where(g => g.Kind == IrGraphKind.Event)
            .ToList();

        WriteLine($"staging.Add({className}.BlueprintId, new global::Fdp.Toolkit.Blueprints.BlueprintDefinition");
        WriteLine("{");
        Indent();
        WriteLine($"Name = \"{asset.Name}\",");
        WriteLine("Kind = global::Fdp.Toolkit.Blueprints.BlueprintDispatchKind.Instance,");
        WriteLine($"StructureHash = {className}.StructureHash,");
        WriteLine($"StateSize = {className}.StateSize,");
        WriteLine($"StateClrType = typeof({className}.State),");
        WriteLine($"InitDefault = {className}.InitDefault,");
        WriteLine($"Tick = {className}.TickThunk,");
        if (eventHandlers.Count > 0)
        {
            WriteLine("EventHandlers = new global::System.Collections.Generic.Dictionary<string, global::Fdp.Toolkit.Blueprints.EventHandlerDelegate>(global::System.StringComparer.Ordinal)");
            WriteLine("{");
            Indent();
            foreach (var evtGraph in eventHandlers)
                WriteLine($"[\"{evtGraph.Name}\"] = {className}.Event_{evtGraph.Name}_Thunk,");
            Outdent();
            WriteLine("},");
        }
        Outdent();
        WriteLine("});");
    }
}
