<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GizmoMap.Contracts\GizmoMap.Contracts.csproj" />
    <ProjectReference Include="..\GizmoMap.Network\GizmoMap.Network.csproj" />
    <ProjectReference Include="..\GizmoMap.Presentation\GizmoMap.Presentation.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CycloneDDS.NET" Version="0.3.2" />
  </ItemGroup>
</Project>
