using System;
using CycloneDDS.Runtime;
using Fdp.Interfaces;
using Fdp.Kernel;
using FDP.Toolkit.Time.Messages;
using ModuleHost.Core.Abstractions;

namespace FDP.Toolkit.Time
{
    /// <summary>
    /// Bridges <see cref="FrameOrderDescriptor"/> and <see cref="FrameAckDescriptor"/> between
    /// the local <see cref="FdpEventBus"/> and CycloneDDS, enabling distributed lockstep
    /// time-stepping across all cluster nodes.
    ///
    /// <para>
    /// <b>Egress — FrameOrder (Master → DDS → Slaves):</b>
    /// <see cref="ScanAndPublish"/> drains any <see cref="FrameOrderDescriptor"/> values that
    /// <see cref="Controllers.SteppedMasterController"/> published to the bus this frame and
    /// writes them to the <c>FrameOrder</c> DDS topic.
    /// On slave nodes the bus never contains self-originated FrameOrder messages so this is a
    /// fast no-op.
    /// </para>
    /// <para>
    /// <b>Egress — FrameAck (Slave → DDS → Master):</b>
    /// <see cref="ScanAndPublish"/> also drains <see cref="FrameAckDescriptor"/> values published
    /// by <see cref="Controllers.SteppedSlaveController"/> and writes them to the <c>FrameAck</c>
    /// DDS topic.
    /// On the master node the bus contains no self-originated FrameAck messages (the master never
    /// publishes its own ACK) so this path is a fast no-op.
    /// Echo-loop prevention guards against re-broadcasting our own ACK that arrived back via DDS
    /// loopback.
    /// </para>
    /// <para>
    /// <b>Ingress — FrameOrder (DDS → Slave bus):</b>
    /// <see cref="PollIngress"/> reads pending <c>FrameOrder</c> DDS samples and publishes them
    /// to the local <see cref="FdpEventBus"/> for <see cref="Controllers.SteppedSlaveController"/>.
    /// </para>
    /// <para>
    /// <b>Ingress — FrameAck (DDS → Master bus):</b>
    /// <see cref="PollIngress"/> reads pending <c>FrameAck</c> DDS samples and publishes them
    /// to the local <see cref="FdpEventBus"/> for <see cref="Controllers.SteppedMasterController"/>
    /// (ACK counting).
    /// </para>
    ///
    /// <para>
    /// Wire one instance per node that participates in distributed stepping.  Both egress and
    /// ingress are always executed; each controller only acts when it finds relevant events in the
    /// bus, so running both sides on every node is harmless and keeps the wiring symmetric.
    /// </para>
    ///
    /// <para>
    /// Register via <see cref="TimeNetworkModule.CreateLockstepTranslator"/> and add the result
    /// to the <c>customTranslators</c> list passed to <c>CycloneNetworkModule</c>, or call
    /// <see cref="ScanAndPublish"/> / <see cref="PollIngress"/> manually each frame.
    /// </para>
    /// </summary>
    public sealed class FrameLockstepDescriptorTranslator : IDescriptorTranslator
    {
        // IDescriptorTranslator identity — use FrameOrder topic as the primary key
        private const string TopicNameValue = "FrameOrder";
        private const long   OrdinalValue   = 202;

        private readonly DdsReader<FrameOrderDescriptor>? _orderReader;
        private readonly DdsWriter<FrameOrderDescriptor>? _orderWriter;
        private readonly DdsReader<FrameAckDescriptor>?   _ackReader;
        private readonly DdsWriter<FrameAckDescriptor>?   _ackWriter;
        private readonly FdpEventBus _eventBus;
        private readonly int _localNodeId;

        // Echo-loop prevention for FrameOrder: only forward a FrameOrderDescriptor to DDS if
        // its FrameID is strictly greater than the last FrameID we forwarded or received from DDS.
        // Without this, the DDS loopback causes stale echoes to keep circulating and can overwrite
        // newer FrameOrders in the reader's KEEP_LAST(1) history, causing slaves to miss a step.
        private long _lastSentOrderFrameId = -1;

        // Echo-loop prevention for FrameAck:
        // Only forward ACKs generated by THIS node (_localNodeId filter).
        // Also track the last FrameID we forwarded so DDS self-loopback cannot re-echo the
        // same ACK: when the ACK arrives back from DDS the FrameID will be <= _lastSentAckFrameId.
        private long _lastSentAckFrameId = -1;

        public string TopicName         => TopicNameValue;
        public long   DescriptorOrdinal => OrdinalValue;

        /// <summary>Creates the translator.</summary>
        /// <param name="participant">
        /// DDS domain participant.  Pass <see langword="null"/> in unit-test environments where
        /// no DDS infrastructure is available — both <see cref="ScanAndPublish"/> and
        /// <see cref="PollIngress"/> become safe no-ops.
        /// </param>
        /// <param name="eventBus">
        /// The local <see cref="FdpEventBus"/> shared with the time controllers on this node.
        /// </param>
        /// <param name="localNodeId">
        /// The node ID of this process.  Used to prevent <see cref="ScanAndPublish"/> from
        /// re-broadcasting ACKs that originated on remote nodes — keeping the master from
        /// flooding DDS with echoes of every slave ACK it just ingressed.
        /// </param>
        public FrameLockstepDescriptorTranslator(DdsParticipant? participant, FdpEventBus eventBus,
            int localNodeId = 0)
        {
            _eventBus = eventBus ?? throw new ArgumentNullException(nameof(eventBus));
            _localNodeId = localNodeId;

            if (participant is not null)
            {
                _orderReader = new DdsReader<FrameOrderDescriptor>(participant);
                _orderWriter = new DdsWriter<FrameOrderDescriptor>(participant);
                _ackReader   = new DdsReader<FrameAckDescriptor>(participant);
                _ackWriter   = new DdsWriter<FrameAckDescriptor>(participant);
            }

            // Pre-register so Consume<T> is safe even before the first Publish warm-up.
            _eventBus.Register<FrameOrderDescriptor>();
            _eventBus.Register<FrameAckDescriptor>();
        }

        // ── Egress ───────────────────────────────────────────────────────────

        /// <summary>
        /// Drains <see cref="FrameOrderDescriptor"/> and <see cref="FrameAckDescriptor"/> from
        /// the bus and publishes them to DDS.  Called every frame by <c>CycloneNetworkModule</c>
        /// or manually.
        /// </summary>
        public void ScanAndPublish(ISimulationView view)
        {
            // ── FrameOrder egress (Master → DDS) ─────────────────────────────
            if (_orderWriter is not null)
            {
                foreach (var order in _eventBus.Consume<FrameOrderDescriptor>())
                {
                    // Suppress duplicate/echo FrameOrders: only forward to DDS if FrameID is
                    // strictly greater than the last one we sent.  DDS loopback can bring old
                    // FrameOrders back into the bus; without this guard they would repeatedly
                    // overwrite newer orders in the reader's KEEP_LAST(1) history queue.
                    if (order.FrameID <= _lastSentOrderFrameId)
                        continue;

                    _orderWriter.Write(order);
                    _lastSentOrderFrameId = order.FrameID;
                }
            }

            // ── FrameAck egress (Slave → DDS) ────────────────────────────────
            if (_ackWriter is not null)
            {
                foreach (var ack in _eventBus.Consume<FrameAckDescriptor>())
                {
                    // Two-level echo prevention:
                    // 1. NodeID filter: only forward ACKs generated by THIS node. ACKs from other
                    //    nodes arrive via DDS PollIngress and must never be re-echoed from here.
                    // 2. FrameID monotonicity: once we've forwarded ACK(F) to DDS, the same sample
                    //    will loop back via DDS self-delivery. Reject any ACK whose FrameID is not
                    //    strictly greater than the last we sent, preventing infinite self-echo.
                    if (ack.NodeID != _localNodeId) continue;
                    if (ack.FrameID <= _lastSentAckFrameId) continue;

                    _ackWriter.Write(ack);
                    _lastSentAckFrameId = ack.FrameID;
                }
            }
        }

        // ── Ingress ──────────────────────────────────────────────────────────

        /// <summary>
        /// Reads pending <c>FrameOrder</c> and <c>FrameAck</c> DDS samples and publishes them
        /// to the local <see cref="FdpEventBus"/>.  Called every frame by
        /// <c>CycloneNetworkModule</c> or manually.
        /// </summary>
        public void PollIngress(IEntityCommandBuffer cmd, ISimulationView view)
        {
            // ── FrameOrder ingress (DDS → Slave bus) ─────────────────────────
            if (_orderReader is not null)
            {
                using var orderLoan = _orderReader.Take();
                foreach (var sample in orderLoan)
                {
                    if (!sample.IsValid) continue;
                    // Update the echo-prevention cursor so ScanAndPublish won't re-broadcast
                    // an order we just received from DDS (the slave echo-loop fix).
                    _lastSentOrderFrameId = sample.Data.FrameID;
                    _eventBus.Publish(sample.Data);
                }
            }

            // ── FrameAck ingress (DDS → Master bus) ──────────────────────────
            if (_ackReader is not null)
            {
                using var ackLoan = _ackReader.Take();
                foreach (var sample in ackLoan)
                {
                    if (!sample.IsValid) continue;
                    _eventBus.Publish(sample.Data);
                }
            }
        }

        // ── Ghost promotion / entity lifecycle — not applicable ──────────────

        /// <inheritdoc/>
        public void ApplyToEntity(Entity entity, object data, EntityRepository repo) { }

        /// <inheritdoc/>
        public void Dispose(long networkEntityId) { }
    }
}
