#ifndef _bdc_sst_sim_desc_h
#define _bdc_sst_sim_desc_h

#include "bdc-sst-common.idl"

// ===================================================================================
// GENERAL PRINCIPLES: BDC SST ENTITY DESCRIPTORS
// ===================================================================================
// An entity in the BDC SST architecture is defined by the aggregation of its descriptors.
// There is no single "Entity Object" transmitted over the network; instead, separate
// DDS topics (Descriptors) share a common EntityId.
//
// Life Cycle:
// - Existence is determined solely by the 'EntityMaster' descriptor.
// - If EntityMaster is ALIVE, the entity exists.
// - If EntityMaster is DISPOSED, the entity is deleted.
//
// Ownership:
// - Ownership is granular per descriptor.
// - The "Owner" is simply the last node that successfully wrote to the topic.
// - To update a descriptor owned by someone else, use 'UpdateEntityDescriptorRequest'.
// ===================================================================================

module Bagira {
module BDC {
module SSTD { // "D" as descriptors

    // Entity position/orientation NOT including any dead reckoning information.
	struct GeoSpatial
	{
		long EntityId; // Entity instance Id

        unsigned long long Time;  // Exercise time stamp the following values are valid for (same as CGFX time, same as windows FILETIME). 0 is reserved for unspecified time.
		DDS::DM::GeoPosition Pos;  // Latitude [deg], longitude [deg], altitude [m] above WGS84 ellipsoid
		DDS::DM::OrientationHPR Rot;  // Heading [deg], pitch [deg], roll [deg]
	};
    #pragma keylist GeoSpatial EntityId
    #pragma topic best_effort transient_local keep_last 1



    // Entity velocity/acc allowing for the dead reckoning and smoothing.
    // Less frequent updates (compared to GeoSpatial) are expected since velocity doesn't change as often as position.
	struct GeoSpatialDR
	{
		long EntityId; // Entity instance Id

		unsigned long long Time; // Exercise time stamp the following values are valid for (same as CGFX time, same as windows FILETIME). 0 is reserved for unspecified time.
		DDS::DM::DAL3 Vel;  // Velocity vector Azim=heading in degrees, Elev=pitch in degrees, Length=speed in m/s
        DDS::DM::DAL3 Acc; // Acceleration vector [m/s^2]; same coordinate system as Vel; full vector used to support turning entities
		DDS::DM::OrientationHPR RotVel; // Angular Velocity; Heading [deg/s], pitch [deg/s], roll [deg/s]
	};
    #pragma keylist GeoSpatialDR EntityId
    #pragma topic best_effort transient_local keep_last 1


    enum eDeadReckoning
    {
        deadrNone,  // No dead reckoning, using GeoSpatial

        // linear interpolation/extrapolation of position using the last known velocity vector and acceleration
        // and angular inter/extrapolation of orientation angles using last known rotational speed
        deadrLinear
        // ...
    };

    enum eSpatialSmoothing
    {
        smoothNone     // No smoothing, last Spatial info is used always
    };

    enum eGroundClamp
    {
        gcNone,         // No ground clamping
        gcNonconformal, // Set just altitude to highest terrain point
        gcConformal    // Set altitude to highest terrain point and orientation according to terrain normal vector
    };

    // How the GeoSpatial descriptor is interpretted.
    // If SpatialMode descriptor not present, defaults (zero values) are assumed.
    struct SpatialMode
    {
		long EntityId; // Entity instance Id

        eGroundClamp GroundClamp; // Type of adjusting the height-coordinate (and orientation) of the entity
        eDeadReckoning DeadReckoning; // Type of foreseeing the future movement
        eSpatialSmoothing Smoothing; // Type of smoothing the entity position/orientation
    };
    #pragma keylist SpatialMode EntityId
    #pragma topic reliability reliable
    #pragma topic durability transient_local
    #pragma topic history keep_last 1



    // Overall damage level of the whole entity
    struct EntityDamage
    {
    	long EntityId; // Entity instance Id

    	float Damage; // total damage level of the whole entity 0=healthy, 100 = fully destroyed/dead

    	// for entity part damage, see CompartmentDamage descriptor
    };
    #pragma keylist EntityDamage EntityId
    #pragma topic reliability reliable
    #pragma topic durability transient_local
    #pragma topic history keep_last 1


};
};
}; // modules

#endif
