#ifndef _bdc_sst_common_h
#define _bdc_sst_common_h


module Bagira
{
module DDS
{
module DM
{

    // [CsharpTypeMap("System.Guid")]
    typedef octet Guid[16];

    // [CsharpTypeMap("System.DateTime")]
    typedef long long DateTime;

    //struct Guid
    //{
    //   octet guid_field[16];
    //};

    // [CsharpTypeMap("Bagira.Dds.FixedString32")]
    typedef char FixedString32[32];

    // Unique identifier of a participating node
    @final
    struct NodeId
    {
    	long AppDomainId; // see DomainType

    	// Individual node; unique within a domain
    	long AppInstanceId; 
    };


    // position in geographical coordinates
    @final
    struct GeoPosition
    {
        // latitude in degrees
        double Latitude;

        // longitude in degrees
        double Longitude;

        // altitude in meters above reference ellipsoid
        double Altitude;
    };

    @final
    struct OrientationHPR
    {
        // angles in degrees
        float Heading;
        float Pitch;
        float Roll;
    };

    // "Direction Angles and Length" 3d vector defined by 2 directional angles and a length
    @final
    struct DAL3
    {
        float Azimuth;
        float Elevation;
        float Length;
    };

};
};
}; // modules

#endif
