#ifndef _bdc_sst_generic_msgs_h
#define _bdc_sst_generic_msgs_h

#include "bdc-sst-all-desc.idl"

// ===================================================================================
// GENERAL PRINCIPLES: BDC SST ENTITY DESCRIPTORS
// ===================================================================================
// An entity in the BDC SST architecture is defined by the aggregation of its descriptors.
// There is no single "Entity Object" transmitted over the network; instead, separate
// DDS topics (Descriptors) share a common EntityId.
//
// Life Cycle:
// - Existence is determined solely by the 'EntityMaster' descriptor.
// - If EntityMaster is ALIVE, the entity exists.
// - If EntityMaster is DISPOSED, the entity is deleted.
//
// Ownership:
// - Ownership is granular per descriptor.
// - The "Owner" is simply the last node that successfully wrote to the topic.
// - To update a descriptor owned by someone else, use 'UpdateEntityDescriptorRequest'.
// ===================================================================================


/*

**Error Codes** :

| Code | Name                              | Description                    |
| ---- | --------------------------------- | ------------------------------ |
| 0    | SUCCESS                           | Operation completed            |
| 1    | ERR_UNKNOWN_DESCRIPTOR_TYPE       | Descriptor type not supported  |
| 2    | ERR_ENTITY_NOT_FOUND              | EntityMaster not ALIVE         |
| 3    | ERR_DESCRIPTOR_INSTANCE_NOT_FOUND | Instance ID invalid            |
| 4    | ERR_NOT_OWNER                     | Request reached non-owner      |
| 5    | ERR_VALIDATION_FAILED             | Invalid value/state transition |
| 6    | ERR_NOT_SUPPORTED                 | Descriptor updates forbidden   |
| 7    | ERR_VERSION_CONFLICT              | currentVersion mismatch        |

*/


module Bagira {
module BDC {
module SSTM { // "M" as messages

    // Message to change the ownership of a descriptor.
    // Used when a node wants to gracefully hand over control of a specific component
    // (e.g., simulation physics) to another node without deleting/recreating data.
    @topic
    struct OwnershipUpdate
    {
        // The unique ID of the entity instance affected.
        @key
        long EntityId; 

        // Unique ID of the descriptor type (e.g., 0=Master, 10=GeoSpatial).
        @key
        long DescrTypeId;

        // ID of the descriptor instance.
        // Non-zero if there are multiple descriptors of the same type per entity instance
        // (e.g., multiple radios, multiple engines).
        // Zero if there is just one descriptor of that type per entity instance.
        @key
        long DescrInstanceId;

        // The NodeId of the participant taking over ownership.
        // The current owner monitors this; if it matches 'NewOwner', it stops publishing.
        // The new owner monitors this; if it matches 'NewOwner', it starts publishing.
        DDS::DM::NodeId NewOwner;
    };
    #pragma topic reliable volatile keep_last 1


// ===================================================================================
// GENERIC REQUESTS (SST UTILITIES)
// ===================================================================================


    // CreateEntityRequest is for asking SOMEONE ELSE to create the entity, to simplify the sender
    // if the sender is NOT the intended owner of the new entity.
    @topic
    struct CreateEntityRequest
    {
        DDS::DM::Guid RequestId;

        // who should own the entity created; {0}=default owner
        DDS::DM::NodeId Owner;

        // Extra info on how to create the entity; might be owner specific; 0=default
        long long Flags;
        
        // Sequence of initial descriptors to populate the new entity.
        // Note: The EntityId inside these descriptors will be ignored/overwritten 
        // by the CGF with the newly allocated ID.
        sequence<SSTD::EntityDescriptorUnion> InitialDescriptors;
    };
    #pragma topic reliable volatile keep_all

    // Acknowledgment for entity creation.
    @topic
    struct CreateEntityAck 
    {
        DDS::DM::Guid RequestId;
        
        // The newly allocated Entity ID (if successful).
        long NewEntityId;

        // 0 = success
        long ErrorCode;
    };
    #pragma topic reliable volatile keep_all



    // Request to update a descriptor owned by another node.
    // SST Standard: "If you don't own it, request it."
    @topic
    struct UpdateEntityDescriptorRequest 
    {
        DDS::DM::Guid RequestId;

        // The Entity ID to update.
        long EntityId;
        
        // The specific Descriptor Type (e.g. 10=GeoSpatial).
        SSTD::EDescriptorType DescriptorType;

        // Secondary ID (for multi-instance descriptors like Articulated Parts).
        long PartId; 
        
        // Optimistic Locking Version.
        // "I believe the current version is X. If it is > X, fail this request."
        long CurrentVersion; 

        // The new data payload.
        SSTD::EntityDescriptorUnion Payload;
    };    
    #pragma topic reliable volatile keep_all


    // Acknowledgment for update requests.
    @topic
    struct UpdateEntityDescriptorAck {
        DDS::DM::Guid RequestId;

        long EntityId;

        // 0 = success
        long ErrorCode;
    };
    #pragma topic reliable volatile keep_all


        // All possible entity attributes we can change (if the entity supports it).
        enum EntityAttribute
        {
            eaName,
            eaGeoPosition
        };

        // Unified attribute payload - what data we provide for the attrinute
        union EntityAttributePayload switch (EntityAttribute) {
            case eaName: string Name;
            case eaGeoPosition: DDS::DM::GeoPosition GeoPosition;
        };

        // SST-compliant entity single field update request
        // GENERIC - reusable across any SST application (map, radio, weather, etc.)
        // Used ONLY for updating attributes indescriptors owned by other participants
        // For own descriptors: write directly to DDS topics
        // Acknowledged by CreateUpdateDeleteEntityAck 
        @topic
        struct UpdateEntityAttributeRequest
        {
            DDS::DM::Guid RequestId;

            long EntityId;
            EntityAttribute AttributeId; // what field to change
            
            EntityAttributePayload Payload;
        };
    #pragma topic reliable volatile keep_all
    


    // Acknowledgment for entity creation, descriptor update, deletion, attribute update.
    @topic
    struct CreateUpdateDeleteEntityAck 
    {
        DDS::DM::Guid RequestId;
        
        // 0 = success
        long ErrorCode;
    };
    #pragma topic reliable volatile keep_all
    
};
};
}; // modules


#endif
