#ifndef _bdc_sst_mission_desc_h
#define _bdc_sst_mission_desc_h

#include "bdc-sst-common.idl"

module Bagira {
module BDC {
module SSTD { // "D" as descriptors


// ==============================================================================
// 1. ENUMS
// ==============================================================================

enum eTaskState {
    TASK_PLANNED,   // Waiting for triggers or sequence
    TASK_ACTIVE,    // Currently executing
    TASK_DONE,      // Completed successfully
    TASK_FAILED,    // Failed execution
    TASK_SKIPPED    // Skipped because a later task was forced active
};

// ==============================================================================
// 2. STRUCTS (DATA BUILDING BLOCKS)
// ==============================================================================

struct MissionTrigger {
    string Type;          // e.g., "LineCrossed", "TimeElapsed"
    string Params;        // JSON string (Schema validated)
};

struct MissionTask {
    DDS::DM::Guid TaskId;            // Unique stringified GUID
    string ExecutingEngine;      // who is going to execute the behavior "CGFX" etc.
    string BehaviorId;           // e.g., "MoveToLocation", could be also bkbId od the doctrine (for CGFX)
    string BehaviorParams;       // JSON string (Schema validated) for the doctrine
    
    sequence<MissionTrigger> Triggers; 
    
    eTaskState State;     // Current status of this specific task
};

// Reusable structure for the "Content" of a mission.
// Used in both the EntityMission state and the REPLACE_MISSION command.
struct MissionPlan {
    // ID of the task currently running. 
    // Must match one of the TaskIds in the Tasks sequence.
    DDS::DM::Guid ActiveTaskId;            // Unique stringified GUID
    
    // Ordered list of all tasks
    sequence<MissionTask> Tasks;
};

// ==============================================================================
// 4. TOPIC: ENTITY MISSION (STATE)
// ==============================================================================

@topic
struct EntityMission {
    @key
    long long EntityId; //@key
    
    // The current state of the mission
    MissionPlan Plan;
};
#pragma topic reliable transient_local keep_last 1


};
};
}; // modules

#endif
