using System;
using System.Collections.Generic;

namespace Hrot.Blueprints.Editor.ActionCatalog;

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

/// <summary>
/// Which host graphs can invoke a given behavior action.
/// Combine with | for multi-host entries.
/// </summary>
[Flags]
public enum BehaviorActionHosts
{
    None      = 0,
    /// <summary>Blueprint (data-flow) graph — dynamic per-param data-IN pins.</summary>
    Blueprint = 1 << 0,
    /// <summary>BTree graph — params authored via Inspector/blackboard binding.</summary>
    BTree     = 1 << 1,
    /// <summary>HSM graph — params authored via Inspector/blackboard binding.</summary>
    Hsm       = 1 << 2,
}

/// <summary>
/// Which catalog contributed this action entry.
/// </summary>
public enum BehaviorActionSource
{
    /// <summary>
    /// Came from <c>IChannelCommandCatalog</c> — a hardcoded or generated channel command.
    /// These are always valid in Blueprint graphs.
    /// </summary>
    ChannelCommand,

    /// <summary>
    /// Came from <c>IActionSchemaExporter</c> with a concrete
    /// <c>[BTreeAction]</c>/<c>[HsmAction]</c>/<c>[SharedAiAction]</c> attribute.
    /// </summary>
    Hardcoded,

    /// <summary>
    /// Came from <c>IActionSchemaExporter</c> — a blueprint-authored AiPrimitive whose
    /// backing struct was generated by the compiler and loaded via hot-reload.
    /// </summary>
    AiPrimitive,
}

// ---------------------------------------------------------------------------
// Entry record
// ---------------------------------------------------------------------------

/// <summary>
/// Describes a single invokable behavior action discovered from any source catalog.
/// </summary>
/// <param name="Id">
/// Canonical stable identity string.
/// <list type="bullet">
///   <item>For <see cref="BehaviorActionSource.ChannelCommand"/> entries:
///     <c>"{ChannelTypeFqn}::{ActionId}"</c>.</item>
///   <item>For schema entries (<see cref="BehaviorActionSource.Hardcoded"/> /
///     <see cref="BehaviorActionSource.AiPrimitive"/>): the FQN string from
///     <c>ActionSchemaEntry.Fqn</c> — i.e. <c>"{DeclaringType.FullName}.{MethodName}"</c>.</item>
/// </list>
/// </param>
/// <param name="DisplayName">Human-readable label, suitable for palette / picker UI.</param>
/// <param name="Category">
/// Optional grouping category (channel type short name for channel commands, or null).
/// </param>
/// <param name="ChannelTypeFqn">
/// FQN of the ECS channel component type, e.g.
/// <c>"Fdp.Toolkit.Behavior.Components.LocomotionChannel"</c>.
/// Non-null only for <see cref="BehaviorActionSource.ChannelCommand"/> entries.
/// </param>
/// <param name="ActionId">
/// Numeric action discriminator within the channel (the <c>ushort</c> from
/// <see cref="Hrot.Blueprints.Core.Compiler.Catalogs.ChannelCommandCatalogEntry.ActionId"/>).
/// Zero for non-channel entries.
/// </param>
/// <param name="ParamsTypeFqn">
/// FQN of the action's parameter DTO type, e.g.
/// <c>"Fdp.Toolkit.Navigation.MoveToParams"</c>.
/// Used by <c>NodePinSchema</c> to reflect data-IN pins.
/// </param>
/// <param name="ValidHosts">
/// Bit-field of which host graphs may invoke this action.
/// </param>
/// <param name="Source">Which source catalog contributed this entry.</param>
public sealed record BehaviorActionEntry(
    string               Id,
    string               DisplayName,
    string?              Category,
    string?              ChannelTypeFqn,
    ushort               ActionId,
    string               ParamsTypeFqn,
    BehaviorActionHosts  ValidHosts,
    BehaviorActionSource Source
);

// ---------------------------------------------------------------------------
// Facade interface
// ---------------------------------------------------------------------------

/// <summary>
/// Unified facade over all behavior-action sources.
/// Enumerates <see cref="BehaviorActionEntry"/> instances from:
/// <list type="bullet">
///   <item><see cref="Hrot.Blueprints.Core.Compiler.Catalogs.IChannelCommandCatalog"/> —
///     channel commands valid in Blueprint graphs.</item>
///   <item><see cref="Hrot.Editor.AiShared.Blackboard.IActionSchemaExporter"/> —
///     hardcoded + AiPrimitive actions valid in BTree/HSM graphs.</item>
/// </list>
/// <para>
/// The catalog rebuilds its internal snapshot when the underlying schema changes
/// (subscribes to <see cref="Hrot.Editor.AiShared.Blackboard.IActionSchemaExporter.Changed"/>).
/// </para>
/// </summary>
public interface IBehaviorActionCatalog
{
    /// <summary>
    /// Returns all known behavior actions.
    /// The returned collection is a snapshot of the current state; it is safe to
    /// iterate without holding a lock.
    /// </summary>
    IReadOnlyList<BehaviorActionEntry> GetActions();

    /// <summary>
    /// Returns all behavior actions valid for the specified <paramref name="host"/>.
    /// Equivalent to <c>GetActions().Where(e => e.ValidHosts.HasFlag(host))</c>
    /// but may be more efficient.
    /// </summary>
    IReadOnlyList<BehaviorActionEntry> GetActions(BehaviorActionHosts host);

    /// <summary>
    /// Raised after the internal snapshot is rebuilt (triggered by
    /// <see cref="Hrot.Editor.AiShared.Blackboard.IActionSchemaExporter.Changed"/>).
    /// </summary>
    event Action? Changed;
}
