<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Kernel\Fdp.Kernel\Fdp.Kernel.csproj" />
    <ProjectReference Include="..\FDP.Toolkit.Behavior\FDP.Toolkit.Behavior.csproj" />
    <ProjectReference Include="..\FDP.Toolkit.Physics\FDP.Toolkit.Physics.csproj" />
  </ItemGroup>
</Project>
