using System;
using System.Collections.Generic;
using ModuleHost.Core.Network.Interfaces;

namespace FDP.Toolkit.NetworkSpawning.Events
{
    /// <summary>
    /// Universal command to spawn an entity locally.
    /// Can be generated by local logic (AI/script) or bridged from a DDS request/ingress translator.
    /// Published onto the FdpEventBus; consumed by NetworkSpawningSystem.
    ///
    /// Design note: defined as a struct (value type) to minimise GC pressure during bulk spawning.
    /// It travels through the Managed event stream (not Native) because it contains
    /// a <see cref="List{T}"/> reference field (<see cref="InitialComponents"/>).
    /// The Kernel's <c>ConsumeManagedEvents&lt;T&gt;</c> has no <c>class</c> constraint,
    /// so managed structs are explicitly supported.
    /// </summary>
    public struct SpawnEntityCommand
    {
        /// <summary>
        /// 0 = request new ID allocation (local authority creates new entity).
        /// Non-zero = replicate an existing network entity (ghost/replica path).
        /// </summary>
        public long NetworkId;

        /// <summary>
        /// TKB template type to instantiate. Must match a registered TkbDatabase entry.
        /// </summary>
        public long TkbType;

        /// <summary>
        /// Raw DIS entity type associated with this spawn (from network descriptors).
        /// </summary>
        public ulong DisType;

        /// <summary>
        /// Node ID that owns/controls this entity.
        /// For SimHost-spawned entities: SimHost's local node ID.
        /// For network-replicated ghosts: the remote node's ID.
        /// </summary>
        public int OwnerNodeId;

        /// <summary>
        /// Reliability mode for the Entity Lifecycle Module handshake.
        /// AllPeers: Entity stays Constructing until all peers ACK (use on authority node).
        /// None:     Entity transitions immediately to Constructing state (use for ghost replicas).
        /// </summary>
        public ReliableInitType InitType;

        /// <summary>
        /// Optional list of ECS component instances to apply on top of TKB template defaults.
        /// Each item is an object whose runtime type is used by EntityComponentReflector
        /// to call world.SetComponent(entity, type, value).
        /// Typical contents: GeoSpatial, EntityInfo, VehicleState, etc.
        /// </summary>
        public List<object> InitialComponents;

        /// <summary>
        /// Optional correlation ID for request tracking (used by gateway pattern).
        /// </summary>
        public Guid RequestId;
    }
}
