using Hrot.Editor.AiShared.Comparison;

namespace Hrot.Editor.AiShared.Tests.Comparison;

public sealed class LlmResponseParserTests
{
    private const string WellFormedText =
        "----- HUMAN SUMMARY -----\n" +
        "The combat behavior in OrcGuard_BT has been refined to be more aggressive\n" +
        "about firing. The previously-single-shot Action node now repeats up to 3\n" +
        "times via a new Repeater decorator, which means the guard will commit to a\n" +
        "burst before re-evaluating threats.\n" +
        "\n" +
        "No other behavior changes were detected. Threat detection logic is unchanged.\n" +
        "\n" +
        "----- STRUCTURED CHANGES (JSON) -----\n" +
        "{\n" +
        "  \"summary\": \"Burst-fire behavior added to OrcGuard combat; ammo tracking variable renamed.\",\n" +
        "  \"changes\": [\n" +
        "    {\n" +
        "      \"kind\": \"node_added\",\n" +
        "      \"elementId\": \"b4711d22-1d22-4c5e-9a3b-2c4d5e6f7a8b\",\n" +
        "      \"elementDescription\": \"Repeater decorator wrapping AimAndFire\",\n" +
        "      \"field\": null,\n" +
        "      \"oldValue\": null,\n" +
        "      \"newValue\": \"Repeater(count: 3)\",\n" +
        "      \"severity\": \"behavior\",\n" +
        "      \"description\": \"AimAndFire now repeats 3 times per Sequence iteration.\"\n" +
        "    },\n" +
        "    {\n" +
        "      \"kind\": \"variable_renamed\",\n" +
        "      \"elementId\": \"BurstShotsRemaining\",\n" +
        "      \"elementDescription\": \"AmmoCount blackboard variable\",\n" +
        "      \"field\": \"name\",\n" +
        "      \"oldValue\": \"AmmoCount\",\n" +
        "      \"newValue\": \"BurstShotsRemaining\",\n" +
        "      \"severity\": \"cosmetic\",\n" +
        "      \"description\": \"Variable renamed for clarity.\"\n" +
        "    }\n" +
        "  ]\n" +
        "}";

    [Fact]
    public void Parse_WellFormedResponse_ParsesAllFieldsAndZeroWarnings()
    {
        var result = LlmResponseParser.Parse(WellFormedText);

        Assert.Equal(2, result.Changes.Count);
        Assert.Empty(result.Warnings);
        Assert.NotNull(result.HumanSummary);
        Assert.Contains("OrcGuard_BT", result.HumanSummary);

        var first = result.Changes[0];
        Assert.Equal("node_added", first.Kind);
        Assert.Equal("b4711d22-1d22-4c5e-9a3b-2c4d5e6f7a8b", first.ElementId);
        Assert.Equal("behavior", first.Severity);

        var second = result.Changes[1];
        Assert.Equal("variable_renamed", second.Kind);
        Assert.Equal("BurstShotsRemaining", second.ElementId);
        Assert.Equal("cosmetic", second.Severity);
    }

    [Fact]
    public void Parse_MarkdownFencedJson_ProducesSameResultAsUnfenced()
    {
        // Wrap the JSON section in ```json ... ```
        var fencedText =
            "----- HUMAN SUMMARY -----\n" +
            "Human summary text.\n" +
            "\n" +
            "----- STRUCTURED CHANGES (JSON) -----\n" +
            "```json\n" +
            "{\n" +
            "  \"summary\": \"Burst-fire behavior added to OrcGuard combat; ammo tracking variable renamed.\",\n" +
            "  \"changes\": [\n" +
            "    {\n" +
            "      \"kind\": \"node_added\",\n" +
            "      \"elementId\": \"b4711d22-1d22-4c5e-9a3b-2c4d5e6f7a8b\",\n" +
            "      \"elementDescription\": \"Repeater decorator wrapping AimAndFire\",\n" +
            "      \"field\": null,\n" +
            "      \"oldValue\": null,\n" +
            "      \"newValue\": \"Repeater(count: 3)\",\n" +
            "      \"severity\": \"behavior\",\n" +
            "      \"description\": \"AimAndFire now repeats 3 times.\"\n" +
            "    },\n" +
            "    {\n" +
            "      \"kind\": \"variable_renamed\",\n" +
            "      \"elementId\": \"BurstShotsRemaining\",\n" +
            "      \"elementDescription\": \"AmmoCount blackboard variable\",\n" +
            "      \"field\": \"name\",\n" +
            "      \"oldValue\": \"AmmoCount\",\n" +
            "      \"newValue\": \"BurstShotsRemaining\",\n" +
            "      \"severity\": \"cosmetic\",\n" +
            "      \"description\": \"Variable renamed for clarity.\"\n" +
            "    }\n" +
            "  ]\n" +
            "}\n" +
            "```";

        var result = LlmResponseParser.Parse(fencedText);

        Assert.Equal(2, result.Changes.Count);
        Assert.Empty(result.Warnings);
    }

    [Fact]
    public void Parse_ExtraLeadingProseBeforeHumanMarker_HumanSummaryCorrectlyExtracted()
    {
        var text =
            "This is a comparison of two BTree assets.\n" +
            "The assets were generated by the Hrot AI editor.\n" +
            "Analysis follows below.\n" +
            WellFormedText;

        var result = LlmResponseParser.Parse(text);

        Assert.Equal(2, result.Changes.Count);
        Assert.Empty(result.Warnings);
        // Human summary should NOT include the extra prose
        Assert.NotNull(result.HumanSummary);
        Assert.DoesNotContain("generated by the Hrot AI editor", result.HumanSummary!);
    }

    [Fact]
    public void Parse_MarkerAbsent_FallbackFirstBraceToLastBrace()
    {
        // No markers -- just raw JSON with some prose before the first {.
        const string text =
            "Here is the analysis:\n" +
            "{\n" +
            "  \"summary\": \"Some change.\",\n" +
            "  \"changes\": [\n" +
            "    {\n" +
            "      \"kind\": \"node_added\",\n" +
            "      \"elementId\": \"abc\",\n" +
            "      \"elementDescription\": \"Some node\",\n" +
            "      \"field\": null,\n" +
            "      \"oldValue\": null,\n" +
            "      \"newValue\": null,\n" +
            "      \"severity\": \"feature\",\n" +
            "      \"description\": \"A new node was added.\"\n" +
            "    }\n" +
            "  ]\n" +
            "}";

        var result = LlmResponseParser.Parse(text);

        Assert.Single(result.Changes);
        Assert.Empty(result.Warnings);
        Assert.Equal("node_added", result.Changes[0].Kind);
    }

    [Fact]
    public void Parse_TruncatedRecoverable_Returns1ChangeAnd1Warning()
    {
        // Well-formed JSON with only first change present; closing ] and } missing.
        const string text =
            "----- HUMAN SUMMARY -----\n" +
            "Summary text.\n" +
            "\n" +
            "----- STRUCTURED CHANGES (JSON) -----\n" +
            "{\n" +
            "  \"summary\": \"Burst-fire behavior added.\",\n" +
            "  \"changes\": [\n" +
            "    {\n" +
            "      \"kind\": \"node_added\",\n" +
            "      \"elementId\": \"b4711d22-1d22-4c5e-9a3b-2c4d5e6f7a8b\",\n" +
            "      \"elementDescription\": \"Repeater decorator wrapping AimAndFire\",\n" +
            "      \"field\": null,\n" +
            "      \"oldValue\": null,\n" +
            "      \"newValue\": \"Repeater(count: 3)\",\n" +
            "      \"severity\": \"behavior\",\n" +
            "      \"description\": \"AimAndFire now repeats 3 times.\"\n" +
            "    }";
        // No closing ] or }

        var result = LlmResponseParser.Parse(text);

        Assert.Single(result.Changes);
        Assert.Single(result.Warnings);
        Assert.Contains("truncated", result.Warnings[0], StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Parse_TruncatedUnrecoverable_Returns0ChangesAnd1Warning()
    {
        // JSON cut mid-key, no complete } to recover from.
        const string text = "{ \"summary\": \"abc\", \"changes\": [{ \"kind\":";

        var result = LlmResponseParser.Parse(text);

        Assert.Empty(result.Changes);
        Assert.Single(result.Warnings);
        Assert.Contains("truncated", result.Warnings[0], StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Parse_UnknownKind_NormalizesToNodeModifiedWithWarning()
    {
        const string text =
            "----- HUMAN SUMMARY -----\nSummary.\n" +
            "----- STRUCTURED CHANGES (JSON) -----\n" +
            "{\n" +
            "  \"summary\": \"Test.\",\n" +
            "  \"changes\": [\n" +
            "    {\n" +
            "      \"kind\": \"totally_unknown_thing\",\n" +
            "      \"elementId\": \"abc\",\n" +
            "      \"elementDescription\": \"Some node\",\n" +
            "      \"field\": null,\n" +
            "      \"oldValue\": null,\n" +
            "      \"newValue\": null,\n" +
            "      \"severity\": \"tuning\",\n" +
            "      \"description\": \"Something changed.\"\n" +
            "    }\n" +
            "  ]\n" +
            "}";

        var result = LlmResponseParser.Parse(text);

        Assert.Single(result.Changes);
        Assert.Equal("node_modified", result.Changes[0].Kind);
        Assert.Single(result.Warnings);
        Assert.Contains("totally_unknown_thing", result.Warnings[0]);
    }

    [Fact]
    public void Parse_UnknownSeverity_NormalizesToTuningWithWarning()
    {
        const string text =
            "----- HUMAN SUMMARY -----\nSummary.\n" +
            "----- STRUCTURED CHANGES (JSON) -----\n" +
            "{\n" +
            "  \"summary\": \"Test.\",\n" +
            "  \"changes\": [\n" +
            "    {\n" +
            "      \"kind\": \"node_modified\",\n" +
            "      \"elementId\": \"abc\",\n" +
            "      \"elementDescription\": \"Some node\",\n" +
            "      \"field\": null,\n" +
            "      \"oldValue\": null,\n" +
            "      \"newValue\": null,\n" +
            "      \"severity\": \"catastrophic\",\n" +
            "      \"description\": \"Something changed.\"\n" +
            "    }\n" +
            "  ]\n" +
            "}";

        var result = LlmResponseParser.Parse(text);

        Assert.Single(result.Changes);
        Assert.Equal("tuning", result.Changes[0].Severity);
        Assert.Single(result.Warnings);
        Assert.Contains("catastrophic", result.Warnings[0]);
    }

    [Fact]
    public void Parse_MissingDescription_FilledWithEmptyStringWithWarning()
    {
        const string text =
            "----- HUMAN SUMMARY -----\nSummary.\n" +
            "----- STRUCTURED CHANGES (JSON) -----\n" +
            "{\n" +
            "  \"summary\": \"Test.\",\n" +
            "  \"changes\": [\n" +
            "    {\n" +
            "      \"kind\": \"node_added\",\n" +
            "      \"elementId\": \"abc\",\n" +
            "      \"elementDescription\": \"Some node\",\n" +
            "      \"field\": null,\n" +
            "      \"oldValue\": null,\n" +
            "      \"newValue\": null,\n" +
            "      \"severity\": \"feature\"\n" +
            "    }\n" +
            "  ]\n" +
            "}";

        var result = LlmResponseParser.Parse(text);

        Assert.Single(result.Changes);
        Assert.Equal("", result.Changes[0].Description);
        Assert.Single(result.Warnings);
        Assert.Contains("description", result.Warnings[0], StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Parse_NullElementId_ParsedNormallyNoWarning()
    {
        const string text =
            "----- HUMAN SUMMARY -----\nSummary.\n" +
            "----- STRUCTURED CHANGES (JSON) -----\n" +
            "{\n" +
            "  \"summary\": \"Test.\",\n" +
            "  \"changes\": [\n" +
            "    {\n" +
            "      \"kind\": \"intent_shift\",\n" +
            "      \"elementId\": null,\n" +
            "      \"elementDescription\": \"Entire subgraph\",\n" +
            "      \"field\": null,\n" +
            "      \"oldValue\": null,\n" +
            "      \"newValue\": null,\n" +
            "      \"severity\": \"behavior\",\n" +
            "      \"description\": \"Overall behavior shifted.\"\n" +
            "    }\n" +
            "  ]\n" +
            "}";

        var result = LlmResponseParser.Parse(text);

        Assert.Single(result.Changes);
        Assert.Null(result.Changes[0].ElementId);
        Assert.Empty(result.Warnings);
    }

    [Fact]
    public void Parse_EmptyChangesArray_ReturnsEmptyChangesNoWarnings()
    {
        const string text =
            "----- HUMAN SUMMARY -----\nNo changes detected.\n" +
            "----- STRUCTURED CHANGES (JSON) -----\n" +
            "{\n" +
            "  \"summary\": \"No changes.\",\n" +
            "  \"changes\": []\n" +
            "}";

        var result = LlmResponseParser.Parse(text);

        Assert.Empty(result.Changes);
        Assert.Empty(result.Warnings);
        Assert.Equal("No changes.", result.TopLevelSummary);
    }

    // TASK-C-20: Parametrized fixture tests
    [Theory]
    [InlineData("well_formed.txt",              2, 0)]
    [InlineData("markdown_fenced.txt",          2, 0)]
    [InlineData("extra_leading_prose.txt",      2, 0)]
    [InlineData("truncated_recoverable.txt",    1, 1)]
    [InlineData("truncated_unrecoverable.txt",  0, 1)]
    [InlineData("unknown_kind.txt",             2, 1)]
    [InlineData("unknown_severity.txt",         2, 1)]
    [InlineData("missing_required_field.txt",   2, 1)]
    [InlineData("unresolvable_element_ids.txt", 2, 0)]
    public void Parse_Fixture_ProducesExpectedCounts(string fixture, int expectedChanges, int expectedWarnings)
    {
        var fixturePath = Path.Combine(AppContext.BaseDirectory, "Comparison", "Fixtures", "Responses", fixture);
        var text = File.ReadAllText(fixturePath);

        var result = LlmResponseParser.Parse(text);

        Assert.Equal(expectedChanges, result.Changes.Count);
        Assert.Equal(expectedWarnings, result.Warnings.Count);
    }
}
