using System;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Fdp.Toolkit.Behavior.Analyzers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Xunit;

namespace Fdp.Toolkit.Tests.Behavior
{
    /// <summary>
    /// <b>W1 / Batch 58 — the hashed-id collision gate.</b>
    ///
    /// <para>
    /// ⛔⛔ <b>What is guarded.</b> <c>HsmActionDispatcher.RegisterAction(ushort id, IntPtr a)</c> is
    /// <c>ActionTable[id] = a;</c> — last writer wins, silently. Two mechanisms feed it in one build:
    /// <b>hashed</b> ids from <see cref="HsmActionGenerator"/> (FNV-1a truncated to 16 bits, anywhere
    /// in 0…65535) and <b>counter-allocated</b> ids from <c>HsmBridgeEmitCore</c> (literals from
    /// <b>100</b> for actions and <b>200</b> for guards, registering <b>no-op stubs</b>).
    /// ⇒ 🔴🔴 a real action whose name hashes into the stub window is replaced by a body that does
    /// nothing, and the HSM behaves correctly everywhere except one state, forever.
    /// </para>
    ///
    /// <para>
    /// ⭐⭐ <b><see cref="TheStubWindowCollision_IsCaught"/> is the fixture that matters.</b> <c>W1</c>
    /// as written says <i>"refuse duplicate HASHED ids"</i> — ⛔ and the stub ids are <b>never
    /// hashed</b>, so a gate built exactly to that spec cannot see them. Without this fixture the
    /// correction is not actually implemented, only claimed.
    /// </para>
    ///
    /// <para>
    /// ⚠ <b>The hashed half runs the REAL generator.</b> Hand-writing what it emits would test the
    /// fixture rather than the pair: the analyzer must match the shape the allocator actually
    /// produces, and the two live in different projects.
    /// </para>
    /// </summary>
    public class HsmDispatcherIdAnalyzerTests
    {
        // ── the surface both halves bind against ────────────────────────────────

        private const string KernelStubs = @"
using System;
namespace Fhsm.Kernel.Data
{
    public struct HsmCommandWriter { }
    public enum CommandLane { None = 0 }
}
namespace Fhsm.Kernel.Attributes
{
    [AttributeUsage(AttributeTargets.Method)]
    public sealed class HsmActionAttribute : Attribute { public string Name { get; set; } }
    [AttributeUsage(AttributeTargets.Method)]
    public sealed class HsmGuardAttribute : Attribute { public string Name { get; set; } }
    [AttributeUsage(AttributeTargets.Class)]
    public sealed class HsmActionRegistrarAttribute : Attribute { }
}
namespace Fhsm.Kernel
{
    using Fhsm.Kernel.Data;
    public static unsafe class HsmActionDispatcher
    {
        public static void RegisterAction(ushort id, IntPtr action) { }
        public static void RegisterGuard(ushort id, IntPtr guard) { }
    }
}
";

        /// <summary>
        /// ⭐ <b>Verbatim <c>HsmBridgeEmitCore</c>'s emitted shape</b>, down to the
        /// <c>// &lt;auto-generated/&gt;</c> header and the <c>__hsActionStub</c> / <c>__hsGuardStub</c>
        /// names. ⚠ The start values <b>100</b> and <b>200</b> are pinned against the real emitter by
        /// <c>HsmBridgeStubWindowTests</c> in the AiEditor generator suite — this project sits below
        /// <c>Hrot.AiEditor.Persistence</c> and cannot reference it, so the two halves are pinned
        /// separately rather than one of them being assumed.
        /// </summary>
        private static string BridgeStubRegistrar(int actionId = 100, int guardId = 200) => $@"
// <auto-generated/>
using System;
using Fhsm.Kernel;
namespace Generated.Bridge
{{
    public static unsafe class HsmShowcaseBridge
    {{
        public static void Register()
        {{
            unsafe
            {{
                static void __hsActionStub(void* inst, void* ctx, Fhsm.Kernel.Data.HsmCommandWriter* w) {{ }}
                HsmActionDispatcher.RegisterAction({actionId},
                    (IntPtr)(delegate*<void*, void*, Fhsm.Kernel.Data.HsmCommandWriter*, void>)&__hsActionStub);
            }}
            unsafe
            {{
                static bool __hsGuardStub(void* inst, void* ctx, ushort ev) => true;
                HsmActionDispatcher.RegisterGuard({guardId},
                    (IntPtr)(delegate*<void*, void*, ushort, bool>)&__hsGuardStub);
            }}
        }}
    }}
}}";

        /// <summary>
        /// One <c>[HsmAction]</c> whose id the caller picks.
        ///
        /// <para>
        /// ⭐⭐ <b>Batch 72 / <c>E6</c> ruling (A): the caller now picks the METHOD NAME, not a
        /// <c>Name =</c> override.</b> The id is <c>FNV(fully-qualified name)</c>, so a display-name
        /// override no longer moves it — see <c>HsmActionKey.ForActionName</c>. ⛔ The fixture had to
        /// move with the ruling: it used to vary <c>Name =</c> while every method was
        /// <c>Method{i}</c>, which under (A) makes every fixture the SAME id.
        /// </para>
        /// </summary>
        private static string ActionSource(params string[] actionNames)
        {
            var body = string.Join("\n", actionNames.Select(n => $@"
        [Fhsm.Kernel.Attributes.HsmAction]
        public static unsafe void {n}(void* inst, void* ctx, Fhsm.Kernel.Data.HsmCommandWriter* w) {{ }}"));

            return "namespace Fixture\n{\n    public static class Nodes\n    {" + body + "\n    }\n}";
        }

        /// <summary>The container the action fixtures live in — half of the id under ruling (A).</summary>
        private const string ActionContainer = "Fixture.Nodes";

        /// <summary>The container the guard fixtures live in.</summary>
        private const string GuardContainer = "Fixture.Guards";

        private static string GuardSource(string guardName) => $@"
namespace Fixture
{{
    public static class Guards
    {{
        [Fhsm.Kernel.Attributes.HsmGuard]
        public static unsafe bool {guardName}(void* inst, void* ctx, ushort ev) => true;
    }}
}}";

        // ── harness ─────────────────────────────────────────────────────────────

        /// <summary>
        /// Runs <see cref="HsmActionGenerator"/> over <paramref name="sources"/>, then runs
        /// <see cref="HsmDispatcherIdAnalyzer"/> over the resulting compilation — ⭐ the generated
        /// registrar included, which is the whole point: every id the rail exists to see lives in an
        /// <c>// &lt;auto-generated/&gt;</c> file.
        /// </summary>
        private static async Task<(ImmutableArray<Diagnostic> Diagnostics, string GeneratedRegistrar)>
            RunAsync(params string[] sources)
        {
            var runtimeDir = Path.GetDirectoryName(typeof(object).Assembly.Location)!;
            var references = new[]
            {
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(Path.Combine(runtimeDir, "System.Runtime.dll")),
                MetadataReference.CreateFromFile(Path.Combine(runtimeDir, "System.Collections.dll")),
            };

            var trees = new[] { KernelStubs }.Concat(sources)
                .Select(s => CSharpSyntaxTree.ParseText(s))
                .ToArray();

            var compilation = CSharpCompilation.Create(
                "Fixture",
                trees,
                references,
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, allowUnsafe: true));

            var driver = CSharpGeneratorDriver.Create(new HsmActionGenerator());
            driver.RunGeneratorsAndUpdateCompilation(compilation, out var output, out _);

            // ⚠ Selected by the generator's hint name, not by content: the kernel stubs above declare
            //   `HsmActionRegistrarAttribute`, so a substring match on the SOURCE picks the wrong tree
            //   and every premise assertion below then checks the stub file.
            var registrar = output.SyntaxTrees
                .Where(t => t.FilePath.EndsWith("HsmActionRegistrar.g.cs", StringComparison.Ordinal))
                .Select(t => t.ToString())
                .FirstOrDefault() ?? "";

            var withAnalyzers = output.WithAnalyzers(
                ImmutableArray.Create<DiagnosticAnalyzer>(new HsmDispatcherIdAnalyzer()));

            return (await withAnalyzers.GetAnalyzerDiagnosticsAsync(), registrar);
        }

        /// <summary>The generator's hash, mirrored so a fixture can search for a name hitting a target.</summary>
        private static ushort Fnv1a16(string name)
        {
            uint hash = 2166136261;
            foreach (char c in name) { hash ^= c; hash *= 16777619; }
            return (ushort)(hash & 0xFFFF);
        }

        /// <summary>
        /// A METHOD name whose fully-qualified form hashes to <paramref name="target"/>.
        /// ⚠ Fails loudly rather than silently returning null.
        ///
        /// <para>
        /// ⭐⭐ <b>Batch 72 / ruling (A): the search runs over <c>{container}.{candidate}</c>, not over
        /// the bare name.</b> That is what the generator hashes now, and a fixture searching the bare
        /// name would hit a target the generator never produces — a fixture testing itself.
        /// </para>
        /// </summary>
        private static string NameHashingTo(ushort target, string prefix = "Act",
                                            string container = ActionContainer)
        {
            for (int i = 0; i < 5_000_000; i++)
            {
                var candidate = prefix + i;
                if (Fnv1a16(container + "." + candidate) == target) return candidate;
            }
            throw new InvalidOperationException(
                $"no {container}.{prefix}* name found hashing to 0x{target:X4} — widen the search");
        }

        /// <summary>The id the generator gives an action fixture named <paramref name="method"/>.</summary>
        private static ushort ActionId(string method) => Fnv1a16(ActionContainer + "." + method);

        /// <summary>The id the generator gives a guard fixture named <paramref name="method"/>.</summary>
        private static ushort GuardId(string method) => Fnv1a16(GuardContainer + "." + method);

        private static int CountOf(ImmutableArray<Diagnostic> diags, string id)
            => diags.Count(d => d.Id == id);

        // ────────────────────────────────────────────────────────────────────────
        // (d) ⭐⭐ THE ONE THAT MATTERS — a real action colliding with the stub window
        // ────────────────────────────────────────────────────────────────────────

        /// <summary>
        /// ⭐⭐⭐ <b>A hashed action id landing inside <c>HsmBridgeEmitCore</c>'s <c>100+</c> window.</b>
        ///
        /// <para>
        /// ⛔ <b>This is the fixture <c>W1</c> as specified cannot pass.</b> The stub id is a literal
        /// counter — never hashed, so never in the hash set — and a gate that ranges over hashed ids
        /// alone reports nothing here while shipping the claim that collisions are covered.
        /// 🔴 The runtime consequence is a real action replaced by <c>__hsActionStub { }</c>: no crash,
        /// no log, one state that quietly does nothing.
        /// </para>
        /// </summary>
        [Fact]
        public async Task TheStubWindowCollision_IsCaught()
        {
            var name = NameHashingTo(100);
            var (diags, registrar) = await RunAsync(ActionSource(name), BridgeStubRegistrar());

            // ⭐ The premise, asserted rather than assumed: the generator really did allocate 100.
            Assert.Contains("RegisterAction(100,", registrar);

            Assert.Equal(2, CountOf(diags, "BHU_020"));   // reported on BOTH participants
            Assert.Contains(diags, d => d.Id == "BHU_020" && d.GetMessage().Contains("__hsActionStub"));
            // ⭐ And it names BOTH sides, so the author can see what the stub displaced.
            // ⚠ Batch 72 / ruling (A): the diagnostic names the FULLY QUALIFIED method, because that is
            //   now what the id is computed from. It used to name the `Name =` override.
            Assert.Contains(diags, d => d.Id == "BHU_020"
                                     && d.GetMessage().Contains($"{ActionContainer}.{name}"));
        }

        /// <summary>
        /// ⭐ The guard half of the same window (<c>200+</c>). ⚠ Stated separately because the two
        /// tables are separate: a fix that only ranged over <c>ActionTable</c> would pass the fixture
        /// above and still miss every guard.
        /// </summary>
        [Fact]
        public async Task TheGuardStubWindowCollision_IsCaught()
        {
            var name = NameHashingTo(200, "Grd", GuardContainer);
            var (diags, registrar) = await RunAsync(GuardSource(name), BridgeStubRegistrar());

            Assert.Contains("RegisterGuard(200,", registrar);
            Assert.Equal(2, CountOf(diags, "BHU_020"));
            Assert.Contains(diags, d => d.Id == "BHU_020" && d.GetMessage().Contains("__hsGuardStub"));
        }

        // ────────────────────────────────────────────────────────────────────────
        // (a) two hashed keys colliding
        // ────────────────────────────────────────────────────────────────────────

        /// <summary>
        /// ⭐ The plain case <c>W1</c> describes: two action names hashing to the same 16-bit id.
        /// ⚠ Sibling precedent <c>UT0103</c>, in the same hash family — <i>"mirror, do not invent"</i>.
        /// </summary>
        [Fact]
        public async Task TwoActionNamesWithTheSameHash_AreRefused()
        {
            const string first = "AlphaAction";
            var target = ActionId(first);            // ⭐ the FQN's hash -- what the generator emits
            var second = NameHashingTo(target, "Coll");

            Assert.NotEqual(first, second);

            var (diags, _) = await RunAsync(ActionSource(first, second));
            Assert.Equal(2, CountOf(diags, "BHU_020"));
        }

        // ────────────────────────────────────────────────────────────────────────
        // (b) (c) the reserved values
        // ────────────────────────────────────────────────────────────────────────

        /// <summary>
        /// 🔴 A name hashing to <b>0</b>. <c>HsmKernelCore</c> guards every action call with
        /// <c>if (…ActionId != 0 &amp;&amp; …ActionId != 0xFFFF)</c> (<c>:304 :448 :669 :682 :714</c>) and
        /// <c>GlobalTransitionDef:19</c> documents <c>0 = none</c> ⇒ the registration succeeds and the
        /// action is then never invoked.
        /// </summary>
        [Fact]
        public async Task AnActionNameHashingToZero_IsRefused()
        {
            var (diags, registrar) = await RunAsync(ActionSource(NameHashingTo(0)));
            Assert.Contains("RegisterAction(0,", registrar);
            Assert.Equal(1, CountOf(diags, "BHU_021"));
        }

        /// <summary>🔴 The other sentinel — <c>0xFFFF</c>, the kernel's invalid-state marker.</summary>
        [Fact]
        public async Task AnActionNameHashingToFFFF_IsRefused()
        {
            var (diags, registrar) = await RunAsync(ActionSource(NameHashingTo(0xFFFF)));
            Assert.Contains("RegisterAction(65535,", registrar);
            Assert.Equal(1, CountOf(diags, "BHU_021"));
        }

        /// <summary>
        /// 🔴🔴 <b>A GUARD hashing to 0 is worse than "never invoked".</b> <c>HsmKernelCore:540</c> and
        /// <c>:583</c> read <c>if (gt.GuardId == 0 || EvaluateGuard(…))</c> ⇒ ⛔ <b>the transition it
        /// was protecting becomes unconditional.</b> ⭐ The message says so, because "reserved id" on
        /// its own would read as harmless.
        /// </summary>
        [Fact]
        public async Task AGuardNameHashingToZero_IsRefused_AndSaysTheGateOpens()
        {
            var (diags, _) = await RunAsync(GuardSource(NameHashingTo(0, "Grd", GuardContainer)));
            var d = Assert.Single(diags.Where(x => x.Id == "BHU_021"));
            Assert.Contains("unconditionally true", d.GetMessage());
        }

        // ────────────────────────────────────────────────────────────────────────
        // the false positives it must NOT report
        // ────────────────────────────────────────────────────────────────────────

        /// <summary>
        /// ⭐⭐ <b>An action and a guard sharing an id is NOT a collision</b> — <c>ActionTable</c> and
        /// <c>GuardTable</c> are two dictionaries. ⚠ Without this the obvious implementation (group by
        /// id) would refuse correct code, and a gate that cries wolf gets suppressed and then guards
        /// nothing.
        /// </summary>
        [Fact]
        public async Task AnActionAndAGuardSharingAnId_AreNotACollision()
        {
            const string actionName = "SharedIdAction";
            var target = ActionId(actionName);       // ⭐ the FQN's hash
            var guardName = NameHashingTo(target, "Grd", GuardContainer);

            var (diags, _) = await RunAsync(ActionSource(actionName), GuardSource(guardName));

            Assert.Equal(0, CountOf(diags, "BHU_020"));
        }

        /// <summary>
        /// ⭐ The corpus shape today: one hashed action and one stub, at <b>different</b> ids. ⛔ Green
        /// here is the claim that this gate does not redden what already builds.
        /// </summary>
        [Fact]
        public async Task DistinctIds_ReportNothing()
        {
            var (diags, _) = await RunAsync(ActionSource("PerfectlyOrdinaryAction"), BridgeStubRegistrar());
            Assert.Empty(diags.Where(d => d.Id == "BHU_020" || d.Id == "BHU_021"));
        }

        /// <summary>
        /// ⚠⚠ <b>The load-bearing configuration, asserted directly.</b> Both halves of the id space live
        /// in <c>// &lt;auto-generated/&gt;</c> files; the sibling <c>UtilityAuthoringAnalyzer</c> sets
        /// <see cref="GeneratedCodeAnalysisFlags.None"/>, which is right for an authoring rule and would
        /// make THIS analyzer pass every test written against hand-written fixtures while seeing
        /// nothing whatsoever in production. ⭐ Here the collision is between two ids that BOTH appear
        /// only inside generated files.
        /// </summary>
        [Fact]
        public async Task IdsInsideGeneratedFiles_AreStillAnalysed()
        {
            // Both registrations carry the auto-generated header; neither is hand-written source.
            var (diags, _) = await RunAsync(
                BridgeStubRegistrar(actionId: 100, guardId: 200),
                BridgeStubRegistrar(actionId: 100, guardId: 201).Replace("HsmShowcaseBridge", "SecondBridge"));

            Assert.Equal(2, CountOf(diags, "BHU_020"));   // the two action-100 registrations
        }
    }
}
