<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Hrot.Editor.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hrot.ScenarioEditor\Hrot.ScenarioEditor.csproj" />
    <ProjectReference Include="..\FDP\Toolkits\FDP.Toolkit.DER\FDP.Toolkit.DER.csproj" />
    <ProjectReference Include="..\Hrot.SimHost\Hrot.SimHost.csproj" />
    <ProjectReference Include="..\Hrot.CGF\Hrot.CGF.csproj" />
    <ProjectReference Include="..\Hrot.Orchestrator\Hrot.Orchestrator.csproj" />
    <ProjectReference Include="..\Hrot.UI.Common\Hrot.UI.Common.csproj" />
    <ProjectReference Include="..\Hrot.Map.Common\Hrot.Map.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="7.0.2" />
    <PackageReference Include="rlImgui-cs" Version="3.2.0" />
    <PackageReference Include="NLog" Version="5.2.8" />
  </ItemGroup>
</Project>
