using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace Fbt.Runtime
{
    /// <summary>
    /// Registry for mapping method names to action delegates.
    /// </summary>
    public class ActionRegistry<TBlackboard, TContext>
        where TBlackboard : struct
        where TContext : struct, IAIContext
    {
        private readonly Dictionary<string, NodeLogicDelegate<TBlackboard, TContext>> _actions 
            = new Dictionary<string, NodeLogicDelegate<TBlackboard, TContext>>();

        private readonly Dictionary<string, NodeDeactivatorDelegate<TBlackboard, TContext>> _deactivators
            = new Dictionary<string, NodeDeactivatorDelegate<TBlackboard, TContext>>();

        /// <summary>
        /// Removes all registered actions and deactivators. Used to release delegate references
        /// into collectible assemblies (hot-reload / test ALC teardown) so they can be GC-reclaimed.
        /// </summary>
        public void Clear()
        {
            _actions.Clear();
            _deactivators.Clear();
        }

        /// <summary>
        /// Register an action delegate with a name.
        /// </summary>
        public void Register(string methodName, NodeLogicDelegate<TBlackboard, TContext> action)
        {
            if (string.IsNullOrEmpty(methodName))
                throw new ArgumentNullException(nameof(methodName));
            
            if (action == null)
                throw new ArgumentNullException(nameof(action));

            _actions[methodName] = action;
        }

        /// <summary>
        /// Try to retrieve an action delegate by name.
        /// </summary>
        public bool TryGetAction(string methodName, [MaybeNullWhen(false)] out NodeLogicDelegate<TBlackboard, TContext> action)
        {
            if (string.IsNullOrEmpty(methodName))
            {
                action = null;
                return false;
            }

            return _actions.TryGetValue(methodName, out action);
        }

        // ---- SharedAi condition / action aliases ---------------------------------
        // Conditions generated by [SharedAiCondition] are stored as NodeLogicDelegate
        // (returning NodeStatus.Success for true, NodeStatus.Failure for false).
        // These aliases provide a semantically distinct API surface for SharedAi callers.

        /// <summary>
        /// Register a condition adapter emitted for a [SharedAiCondition]-annotated method.
        /// Internally identical to <see cref="Register"/>; the distinct name documents intent.
        /// </summary>
        public void RegisterCondition(string key, NodeLogicDelegate<TBlackboard, TContext> condition)
            => Register(key, condition);

        /// <summary>
        /// Try to retrieve a condition adapter registered via <see cref="RegisterCondition"/>.
        /// Internally identical to <see cref="TryGetAction"/>; the distinct name documents intent.
        /// </summary>
        public bool TryGetCondition(string key, [MaybeNullWhen(false)] out NodeLogicDelegate<TBlackboard, TContext> condition)
            => TryGetAction(key, out condition);

        // ---- Deactivator support -------------------------------------------------

        /// <summary>
        /// Register a deactivator delegate paired with the given action key.
        /// Last-write-wins on duplicate key. Throws <see cref="ArgumentNullException"/>
        /// for null key or null delegate.
        /// </summary>
        public void RegisterDeactivator(string key, NodeDeactivatorDelegate<TBlackboard, TContext> deactivator)
        {
            if (string.IsNullOrEmpty(key))
                throw new ArgumentNullException(nameof(key));
            if (deactivator == null)
                throw new ArgumentNullException(nameof(deactivator));
            _deactivators[key] = deactivator;
        }

        /// <summary>
        /// Try to retrieve a deactivator delegate by action key.
        /// Returns <c>false</c> and a null output when no deactivator is registered for the key.
        /// </summary>
        public bool TryGetDeactivator(string key, [MaybeNullWhen(false)] out NodeDeactivatorDelegate<TBlackboard, TContext> deactivator)
        {
            if (string.IsNullOrEmpty(key))
            {
                deactivator = null;
                return false;
            }
            return _deactivators.TryGetValue(key, out deactivator);
        }
    }
}
