using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Fdp.Toolkit.Behavior.Analyzers
{
    [Generator]
    public class EqsTemplateGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var candidateClasses = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
                    transform: static (ctx, _) => GetEqsTemplateInfo(ctx))
                .Where(static t => t != null);

            var compilationAndClasses = context.CompilationProvider.Combine(candidateClasses.Collect());

            context.RegisterSourceOutput(
                compilationAndClasses,
                static (spc, source) => Execute(spc, source.Left, source.Right!));
        }

        private static EqsTemplateInfo? GetEqsTemplateInfo(GeneratorSyntaxContext context)
        {
            var classDecl = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
            if (symbol == null) return null;

            var attr = symbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "EqsTemplateAttribute");
            if (attr == null) return null;

            // Read assetId from positional constructor arg index 0.
            if (attr.ConstructorArguments.Length == 0) return null;
            if (attr.ConstructorArguments[0].Value is not string assetId) return null;

            // Compute 32-bit FNV-1a hash for BlueprintId.
            uint blueprintId = 2166136261u;
            foreach (char c in assetId)
            {
                blueprintId ^= (uint)c;
                blueprintId *= 16777619u;
            }

            return new EqsTemplateInfo(symbol.ToDisplayString(), assetId, (int)blueprintId);
        }

        private static void Execute(
            SourceProductionContext context,
            Compilation compilation,
            ImmutableArray<EqsTemplateInfo?> templates)
        {
            if (templates.Length == 0) return;

            var valid = templates.Where(t => t != null).Select(t => t!).ToList();
            if (valid.Count == 0) return;

            string assemblyName = (compilation.AssemblyName ?? "Generated").Replace(".", "_");
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Fdp.Toolkit.Blueprints;");
            sb.AppendLine("using Fdp.Toolkit.Blueprints.Attributes;");
            sb.AppendLine("using Fdp.Toolkit.Spatial.Eqs;");
            sb.AppendLine();
            sb.AppendLine("namespace Fdp.Toolkit.Spatial.Eqs.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    [BlueprintRegistrar]");
            sb.AppendLine("    public static class EqsRegistrar_" + assemblyName);
            sb.AppendLine("    {");
            sb.AppendLine("        public static void Register(BlueprintRegistryStaging staging)");
            sb.AppendLine("        {");

            foreach (var t in valid)
            {
                sb.AppendLine("            var template_" + t.BlueprintId + " = " + t.FullyQualifiedName + ".Build(new EqsTemplateBuilder());");
                sb.AppendLine("            staging.Add(" + t.BlueprintId + ", new BlueprintDefinition");
                sb.AppendLine("            {");
                sb.AppendLine("                Name = \"" + t.FullyQualifiedName + "\",");
                sb.AppendLine("                Kind = BlueprintDispatchKind.Library,");
                sb.AppendLine("                StructureHash = template_" + t.BlueprintId + ".ComputeStructureHash(),");
                sb.AppendLine("                StateSize = 0,");
                sb.AppendLine("            });");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("EqsRegistrar_" + assemblyName + ".g.cs", sb.ToString());
        }

        private sealed class EqsTemplateInfo
        {
            public string FullyQualifiedName { get; }
            public string AssetId            { get; }
            public int    BlueprintId        { get; }

            public EqsTemplateInfo(string fullyQualifiedName, string assetId, int blueprintId)
            {
                FullyQualifiedName = fullyQualifiedName;
                AssetId            = assetId;
                BlueprintId        = blueprintId;
            }
        }
    }
}
