using System;
using Fdp.Core;
using Fdp.ModuleHost.Abstractions;
using Fdp.Toolkit.Spatial.Eqs;
using Hrot.SimHost.Systems;

namespace Hrot.SimHost.Modules
{
    /// <summary>
    /// SoD (Separation-of-Duties) module that drives the Phase 1 stub
    /// <see cref="EqsSolverSystem"/> at 10 Hz on a background thread.
    ///
    /// <para>Registered on the Muscle node so the solver can query entities with
    /// <c>EqsSensor</c> and emit <c>EqsResultEvent</c> for <c>EqsResultUpdateSystem</c>
    /// to consume on the Brain side.</para>
    ///
    /// <para><c>AreaQuerySolverSystem</c> continues to run inside
    /// <see cref="CognitiveSpatialModule"/> unchanged; this module no longer delegates
    /// to it.</para>
    ///
    /// <para>EQS templates registered via [BlueprintRegistrar] generated by EqsTemplateGenerator
    /// are picked up automatically by AiHotReloadCoordinator on assembly load.</para>
    /// </summary>
    public sealed class EqsModule : IEcsModule, IDisposable
    {
        /// <inheritdoc/>
        public string Name => "Eqs";

        /// <inheritdoc/>
        /// <remarks>Runs asynchronously at 10 Hz against a SoD snapshot.</remarks>
        public ExecutionPolicy Policy => ExecutionPolicy.SlowBackground(10);

        private readonly EqsSolverSystem _solver = new();

        // Captured on first Tick so Dispose can release the native EqsResultPool ring buffer.
        private EntityRepository? _repo;

        /// <inheritdoc/>
        public void RegisterSystems(ISystemRegistry registry) { }

        /// <inheritdoc/>
        public void Tick(ISimulationView view, float deltaTime)
        {
            if (view is EntityRepository repo)
            {
                // Keep a handle so Dispose can free the Allocator.Persistent result pool.
                _repo = repo;

                // Lazy-init global solver state.
                if (!repo.HasSingleton<EqsSolverGlobalState>())
                    repo.SetSingletonUnmanaged(new EqsSolverGlobalState
                    {
                        MaxAccurateRaycastsPerSolverTick = 2048,
                        AccurateRaysSubmittedThisTick    = 0,
                    });

                // Reset per-tick ray budget at the start of each EqsModule.Tick before the solver runs.
                ref var gs = ref repo.GetSingletonUnmanaged<EqsSolverGlobalState>();
                gs.AccurateRaysSubmittedThisTick = 0;
            }
            _solver.Execute(view, deltaTime);
        }

        /// <summary>
        /// Releases the <see cref="EqsResultPool"/> native ring buffer, which the solver
        /// (or <c>NavigationSolverComponentRegistry.RegisterAll</c>) allocates with
        /// <c>Allocator.Persistent</c>. The kernel disposes modules implementing
        /// <see cref="IDisposable"/> on teardown (see <c>ModuleHostKernel</c>), mirroring
        /// <see cref="CognitiveSpatialModule"/>'s ownership of its persistent spatial grid.
        /// </summary>
        public void Dispose()
        {
            if (_repo is null) return;

            if (_repo.HasSingleton<EqsResultPool>())
            {
                ref var pool = ref _repo.GetSingletonUnmanaged<EqsResultPool>();
                if (pool.Results.IsCreated)
                    pool.Results.Dispose();
            }

            _repo = null;
        }
    }
}
