<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>FDP.Toolkit.Vis2D</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Kernel\Fdp.Core\Fdp.Core.csproj" />
    <PackageReference Include="Raylib-cs" Version="7.0.2" />
    <PackageReference Include="ImGui.NET" Version="1.91.0.1" />
  </ItemGroup>
</Project>
