using System;
using System.Collections.Generic;
using Fdp.Interfaces;
using Fdp.Toolkit.Tkb.Domain;

namespace Fdp.Toolkit.Tkb.Parameters
{
    /// <summary>Where a resolved parameter value came from. 📄 docs/DESIGN_Terrain_Combat_Tuning.md §2, §2a.</summary>
    public enum ParameterProvenance : byte
    {
        /// <summary>Stated by the TKB type.</summary>
        Explicit = 0,
        /// <summary>Derived by a formula from the type's own driving values (<see cref="TkbGeneratedValuesDto"/>).</summary>
        Generated = 1,
        /// <summary>A Reference Library entry matched by DIS type (Stage 3 — the generated library).</summary>
        ReferenceByDis = 2,
        /// <summary>A Reference Library entry matched by name (Stage 3).</summary>
        ReferenceByName = 3,
        /// <summary>An <see cref="EngineFallbacks"/> constant — the type said nothing.</summary>
        EngineFallback = 4,
        /// <summary>The parameter does not exist for this type (e.g. no combat platform ⇒ no Health).</summary>
        NotApplicable = 5,
    }

    /// <summary>One resolved value with its provenance; <see cref="Source"/> names the field, formula or fallback.</summary>
    public readonly record struct ResolvedParameter(string Name, float? Value, ParameterProvenance Provenance, string Source);

    /// <summary>The parameter names <see cref="ParameterResolver"/> answers and <see cref="TkbGeneratedValuesDto"/> keys by.</summary>
    public static class ParameterNames
    {
        public const string MaxHealth      = "Health.Max";
        public const string ArmourFront    = "Armour.Front";
        public const string ArmourSide     = "Armour.Side";
        public const string ArmourRear     = "Armour.Rear";
        public const string ColliderRadius = "Collider.Radius";
        public const string EyeStanding    = "Sensor.EyeHeight.Standing";
        public const string EyeCrouched    = "Sensor.EyeHeight.Crouched";
        public const string EyeProne       = "Sensor.EyeHeight.Prone";

        /// <summary><c>Weapon[i].MuzzleVelocity</c> etc. — per mount.</summary>
        public static string Mount(int index, string field) => $"Weapon[{index}].{field}";
        public const string MuzzleVelocity = "MuzzleVelocity";
        public const string DamagePerHit   = "DamagePerHit";
        public const string Penetration    = "Penetration";
        public const string Range          = "Range";
        public const string DispersionMils = "DispersionMils";
    }

    /// <summary>
    /// ⭐⭐ THE PARAMETER RESOLVER — buildings programme Stage 0 (📄 docs/DESIGN_Terrain_Combat_Tuning.md §2, §6 T-0).
    /// Answers "what value does this type use, and WHERE did it come from" for every combat/perception parameter the
    /// engine defaults today. Chain: <b>explicit TKB data → generated by a builder formula → engine fallback</b>; the
    /// Reference Library step (by DIS / by name) lands with the generator in Stage 3.
    /// <para>⭐⭐ The translators and the fire chain call THESE rules, so <c>GET /tkb/resolve</c> reports exactly what the
    /// simulation uses — it never recomputes on its own.</para>
    /// </summary>
    public static class ParameterResolver
    {
        /// <summary>Every parameter of <paramref name="template"/>, in a stable order (platform, collider, sensors, mounts).</summary>
        public static IReadOnlyList<ResolvedParameter> ResolveAll(TkbTemplate template)
        {
            if (template == null) throw new ArgumentNullException(nameof(template));
            var list = new List<ResolvedParameter>
            {
                MaxHealth(template),
                Armour(template, ParameterNames.ArmourFront),
                Armour(template, ParameterNames.ArmourSide),
                Armour(template, ParameterNames.ArmourRear),
                ColliderRadius(template),
                EyeHeight(template, ParameterNames.EyeStanding),
                EyeHeight(template, ParameterNames.EyeCrouched),
                EyeHeight(template, ParameterNames.EyeProne),
            };
            var suite = template.GetDescriptor<WeaponSuiteDto>();
            if (suite != null)
                for (int i = 0; i < suite.Mounts.Count; i++)
                {
                    list.Add(MuzzleVelocity(template, i));
                    list.Add(DamagePerHit(template, i));
                    list.Add(Penetration(template, i));
                    list.Add(MountRange(template, i));
                    list.Add(Dispersion(template, i));
                }
            return list;
        }

        /// <summary><c>Health.Max</c> — what <c>CombatTkbTranslator</c> stamps; no <see cref="CombatPlatformDefDto"/> ⇒ no Health.</summary>
        public static ResolvedParameter MaxHealth(TkbTemplate t)
        {
            var p = t.GetDescriptor<CombatPlatformDefDto>();
            if (p == null) return NotApplicable(ParameterNames.MaxHealth, "no CombatPlatformDefDto ⇒ no Health component");
            return Stated(t, ParameterNames.MaxHealth, p.MaxHealth, "CombatPlatformDefDto.MaxHealth");
        }

        /// <summary><c>Armour.Front/Side/Rear</c> (mm RHA); a platform without the field reads 0 = unarmoured.</summary>
        public static ResolvedParameter Armour(TkbTemplate t, string name)
        {
            var p = t.GetDescriptor<CombatPlatformDefDto>();
            if (p == null) return NotApplicable(name, "no CombatPlatformDefDto ⇒ unarmoured");
            float v = name switch
            {
                ParameterNames.ArmourFront => p.ArmorFront,
                ParameterNames.ArmourSide  => p.ArmorSide,
                ParameterNames.ArmourRear  => p.ArmorRear,
                _ => throw new ArgumentOutOfRangeException(nameof(name), name, "not an armour face"),
            };
            return Stated(t, name, v, "CombatPlatformDefDto." + name.Replace("Armour.", "Armor"));
        }

        /// <summary>
        /// <c>Collider.Radius</c> — a kinematics descriptor sizes it (<c>max(length, width) / 2</c>,
        /// <c>VehicleKinematicsTkbTranslator</c>); a combat platform without one gets <see cref="EngineFallbacks.ColliderRadius"/>.
        /// </summary>
        public static ResolvedParameter ColliderRadius(TkbTemplate t)
        {
            var v = t.GetDescriptor<VehicleParametersDto>();
            if (v != null)
                return new(ParameterNames.ColliderRadius, MathF.Max(v.Length, v.Width) / 2f, ParameterProvenance.Generated,
                    $"max(length, width) / 2 (length = {v.Length}, width = {v.Width})");
            if (t.GetDescriptor<CombatPlatformDefDto>() != null)
                return Fallback(ParameterNames.ColliderRadius, EngineFallbacks.ColliderRadius, nameof(EngineFallbacks.ColliderRadius));
            return NotApplicable(ParameterNames.ColliderRadius, "no VehicleParametersDto and no CombatPlatformDefDto ⇒ no collider");
        }

        /// <summary>
        /// <c>Sensor.EyeHeight.*</c> — <c>PerceptionTkbTranslator</c>'s rule: if the type states ANY eye height it gets a
        /// <c>SensorMount</c> (standing else 1.7; crouched/prone else = standing); otherwise the LOS strategy's default
        /// soldier mount applies.
        /// </summary>
        public static ResolvedParameter EyeHeight(TkbTemplate t, string name)
        {
            var s = t.GetDescriptor<SensorCapabilitiesDto>();
            bool stated = s != null && (s.EyeHeightStanding > 0f || s.EyeHeightCrouched > 0f || s.EyeHeightProne > 0f);
            if (!stated)
                return name switch
                {
                    ParameterNames.EyeStanding => Fallback(name, EngineFallbacks.EyeHeightStanding, nameof(EngineFallbacks.EyeHeightStanding)),
                    ParameterNames.EyeCrouched => Fallback(name, EngineFallbacks.EyeHeightCrouched, nameof(EngineFallbacks.EyeHeightCrouched)),
                    ParameterNames.EyeProne    => Fallback(name, EngineFallbacks.EyeHeightProne, nameof(EngineFallbacks.EyeHeightProne)),
                    _ => throw new ArgumentOutOfRangeException(nameof(name), name, "not an eye height"),
                };

            var standing = s!.EyeHeightStanding > 0f
                ? new ResolvedParameter(ParameterNames.EyeStanding, s.EyeHeightStanding, ParameterProvenance.Explicit, "SensorCapabilitiesDto.EyeHeightStanding")
                : Fallback(ParameterNames.EyeStanding, EngineFallbacks.EyeHeightStanding, nameof(EngineFallbacks.EyeHeightStanding));
            if (name == ParameterNames.EyeStanding) return standing;
            float own = name switch
            {
                ParameterNames.EyeCrouched => s.EyeHeightCrouched,
                ParameterNames.EyeProne    => s.EyeHeightProne,
                _ => throw new ArgumentOutOfRangeException(nameof(name), name, "not an eye height"),
            };
            return own > 0f
                ? new(name, own, ParameterProvenance.Explicit, "SensorCapabilitiesDto." + name.Replace("Sensor.", "").Replace(".", ""))
                : new(name, standing.Value, ParameterProvenance.Generated, $"= standing ({standing.Value})");
        }

        /// <summary><c>Weapon[i].MuzzleVelocity</c> — the mount's value, else <see cref="EngineFallbacks.MuzzleVelocity"/>.</summary>
        public static ResolvedParameter MuzzleVelocity(TkbTemplate t, int mount)
        {
            var name = ParameterNames.Mount(mount, ParameterNames.MuzzleVelocity);
            var m = Mount(t, mount);
            if (m == null) return NotApplicable(name, "no such mount");
            return m.MuzzleVelocity > 0f
                ? Stated(t, name, m.MuzzleVelocity, $"WeaponSuiteDto.Mounts[{mount}].MuzzleVelocity")
                : Fallback(name, EngineFallbacks.MuzzleVelocity, nameof(EngineFallbacks.MuzzleVelocity));
        }

        /// <summary><c>Weapon[i].DamagePerHit</c> — the mount's value, else <see cref="EngineFallbacks.BulletDamage"/>
        /// (the rule <c>FireProcessingSystem</c> and <c>ArmorModel</c> apply: <see cref="EngineFallbacks.DamageOrFallback"/>).</summary>
        public static ResolvedParameter DamagePerHit(TkbTemplate t, int mount)
        {
            var name = ParameterNames.Mount(mount, ParameterNames.DamagePerHit);
            var m = Mount(t, mount);
            if (m == null) return NotApplicable(name, "no such mount");
            return m.DamagePerHit > 0f
                ? Stated(t, name, m.DamagePerHit, $"WeaponSuiteDto.Mounts[{mount}].DamagePerHit")
                : Fallback(name, EngineFallbacks.BulletDamage, nameof(EngineFallbacks.BulletDamage));
        }

        /// <summary><c>Weapon[i].Penetration</c> (mm RHA) — 0 means no armour model: the hit does flat damage
        /// (<c>ArmorModel</c>).</summary>
        public static ResolvedParameter Penetration(TkbTemplate t, int mount)
        {
            var name = ParameterNames.Mount(mount, ParameterNames.Penetration);
            var m = Mount(t, mount);
            if (m == null) return NotApplicable(name, "no such mount");
            return m.Penetration > 0f
                ? Stated(t, name, m.Penetration, $"WeaponSuiteDto.Mounts[{mount}].Penetration")
                : new(name, 0f, ParameterProvenance.EngineFallback, "0 = no armour model (flat damage per hit)");
        }

        /// <summary><c>Weapon[i].Range</c> (m) — 0 = not declared.</summary>
        public static ResolvedParameter MountRange(TkbTemplate t, int mount)
        {
            var name = ParameterNames.Mount(mount, ParameterNames.Range);
            var m = Mount(t, mount);
            if (m == null) return NotApplicable(name, "no such mount");
            return m.Range > 0f
                ? Stated(t, name, m.Range, $"WeaponSuiteDto.Mounts[{mount}].Range")
                : new(name, 0f, ParameterProvenance.EngineFallback, "0 = not declared");
        }

        /// <summary><c>Weapon[i].DispersionMils</c> — ⭐ AQ85 C: 0 = exact aim (every round flies at the target).</summary>
        public static ResolvedParameter Dispersion(TkbTemplate t, int mount)
        {
            var name = ParameterNames.Mount(mount, ParameterNames.DispersionMils);
            var m = Mount(t, mount);
            if (m == null) return NotApplicable(name, "no such mount");
            return m.DispersionMils > 0f
                ? Stated(t, name, m.DispersionMils, $"WeaponSuiteDto.Mounts[{mount}].DispersionMils")
                : new(name, 0f, ParameterProvenance.EngineFallback, "0 = exact aim (AQ85: a type opts in)");
        }

        private static WeaponMountDto? Mount(TkbTemplate t, int i)
        {
            var suite = t.GetDescriptor<WeaponSuiteDto>();
            return suite != null && i >= 0 && i < suite.Mounts.Count ? suite.Mounts[i] : null;
        }

        /// <summary>A value the template carries: <c>Generated</c> when a builder recorded a formula for it, else <c>Explicit</c>.</summary>
        private static ResolvedParameter Stated(TkbTemplate t, string name, float value, string field)
        {
            var gen = t.GetDescriptor<TkbGeneratedValuesDto>();
            return gen != null && gen.Formulas.TryGetValue(name, out var formula)
                ? new(name, value, ParameterProvenance.Generated, formula)
                : new(name, value, ParameterProvenance.Explicit, field);
        }

        private static ResolvedParameter Fallback(string name, float value, string constant)
            => new(name, value, ParameterProvenance.EngineFallback, "EngineFallbacks." + constant);

        private static ResolvedParameter NotApplicable(string name, string why)
            => new(name, null, ParameterProvenance.NotApplicable, why);
    }
}
