<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\StructEdit.Core\StructEdit.Core.csproj" />
    <ProjectReference Include="..\..\src\StructEdit.Reflection\StructEdit.Reflection.csproj" />
    <ProjectReference Include="..\..\src\StructEdit.Json\StructEdit.Json.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
