<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GizmoMap.Contracts\GizmoMap.Contracts.csproj" />
    <ProjectReference Include="..\GizmoMap.Network\GizmoMap.Network.csproj" />
    <ProjectReference Include="..\..\..\FDP\ExtDeps\StructEdit\src\StructEdit.Core\StructEdit.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="7.0.2" />
    <PackageReference Include="rlImgui-cs" Version="3.2.0" />
    <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
  </ItemGroup>
</Project>
