using System.Text;
using Fdp.Toolkit.Blueprints;
using Hrot.Blueprints.Core.Assets;
using Hrot.Blueprints.Core.Compiler.Ir;
using AssetDispatch = Hrot.Blueprints.Core.Assets.BlueprintDispatchKind;

namespace Hrot.Blueprints.Core.Compiler.Emit;

internal sealed class CSharpEmitter
{
    private readonly StringBuilder _sb = new();
    private readonly DebugMapBuilder _debugMap;
    private readonly EmissionContext _ctx;
    private int _indent;
    private int _currentLine = 1;

    public CSharpEmitter(EmissionContext ctx)
    {
        _ctx = ctx;
        _debugMap = new DebugMapBuilder(ctx.Asset.AssetId, ctx.Asset.BlueprintId, ctx.Asset.StructureHash);
    }

    public EmissionContext Ctx => _ctx;
    public int CurrentLine => _currentLine;

    public void Write(string text)
    {
        _sb.Append(text);
        foreach (char c in text)
            if (c == '\n') _currentLine++;
    }

    public void WriteLine(string line = "")
    {
        for (int i = 0; i < _indent; i++) _sb.Append("    ");
        _sb.Append(line);
        _sb.Append('\n');
        _currentLine++;
    }

    public void Indent() => _indent++;
    public void Outdent() => _indent = Math.Max(0, _indent - 1);

    public void EmitNodeStart(IrDebugAnnotation? debug)
    {
        if (debug?.NodeId is null) return;
        _debugMap.RecordNodeStart(debug.NodeId.Value, debug.GraphId, _currentLine);
    }

    public void EmitNodeEnd(IrDebugAnnotation? debug)
    {
        if (debug?.NodeId is null) return;
        _debugMap.RecordNodeEnd(debug.NodeId.Value, _currentLine);
    }

    public (string Source, DebugMap DebugMap) Emit(IrAsset asset)
    {
        EmitFileHeader(asset);
        EmitUsings();
        WriteLine();

        switch (asset.Dispatch)
        {
            case AssetDispatch.Library:
                LibraryEmitter.EmitClass(this, asset);
                break;
            case AssetDispatch.AiPrimitive:
                AiPrimitiveEmitter.EmitClass(this, asset);
                break;
            case AssetDispatch.Instance:
                InstanceEmitter.EmitClass(this, asset);
                break;
            default:
                throw new NotSupportedException($"Unknown dispatch kind: {asset.Dispatch}");
        }

        WriteLine();
        EmitRegistrarClass(asset);
        return (_sb.ToString(), _debugMap.Build());
    }

    private void EmitFileHeader(IrAsset asset)
    {
        WriteLine("// <auto-generated />");
        WriteLine($"// Asset: {asset.Name} ({asset.AssetId})");
        WriteLine($"// BlueprintId: 0x{asset.BlueprintId:X8}");
        WriteLine($"// StructureHash: 0x{asset.StructureHash:X16}");
        WriteLine();
    }

    private void EmitUsings()
    {
        WriteLine("using System;");
        WriteLine("using System.Runtime.CompilerServices;");
        WriteLine("using System.Runtime.InteropServices;");
        WriteLine("using System.Numerics;");
        WriteLine("using Fdp.Core;");
        WriteLine("using Fdp.Interfaces;");
        WriteLine("using Fdp.ModuleHost.Abstractions;");
        WriteLine("using Fdp.Toolkit.Blueprints;");
    }

    private void EmitRegistrarClass(IrAsset asset)
    {
        var className = $"{asset.SanitizedName}_{asset.BlueprintId:X8}_Bp";
        var registrarName = $"BlueprintRegistrar_{asset.SanitizedName}_{asset.BlueprintId:X8}_Bp";

        bool needsBehReg = asset.Hostings.Any(h =>
            h == AiPrimitiveHosting.BTreeAction || h == AiPrimitiveHosting.BTreeCondition);

        WriteLine("[global::Fdp.Toolkit.Blueprints.Attributes.BlueprintRegistrar]");
        WriteLine($"public static class {registrarName}");
        WriteLine("{");
        Indent();

        var paramParts = new System.Collections.Generic.List<string>
            { "global::Fdp.Toolkit.Blueprints.BlueprintRegistryStaging staging" };
        if (needsBehReg)
            paramParts.Add("global::Fdp.Toolkit.Behavior.BehaviorRegistry behReg");
        var paramSig = string.Join(", ", paramParts);

        WriteLine($"public static void Register({paramSig})");
        WriteLine("{");
        Indent();

        switch (asset.Dispatch)
        {
            case AssetDispatch.Library:
                EmitLibraryRegistration(className, asset);
                break;
            case AssetDispatch.AiPrimitive:
                EmitAiPrimitiveRegistration(className, asset, needsBehReg);
                break;
            case AssetDispatch.Instance:
                EmitInstanceRegistration(className, asset);
                break;
        }

        Outdent();
        WriteLine("}");
        Outdent();
        WriteLine("}");
    }

    private void EmitLibraryRegistration(string className, IrAsset asset)
    {
        WriteLine($"staging.Add({className}.BlueprintId, new global::Fdp.Toolkit.Blueprints.BlueprintDefinition");
        WriteLine("{");
        Indent();
        WriteLine($"Name = \"{asset.Name}\",");
        WriteLine("Kind = global::Fdp.Toolkit.Blueprints.BlueprintDispatchKind.Library,");
        WriteLine($"StructureHash = {asset.StructureHash}UL,");
        WriteLine("StateSize = 0,");
        Outdent();
        WriteLine("});");
    }

    private void EmitAiPrimitiveRegistration(string className, IrAsset asset, bool needsBehReg)
    {
        WriteLine($"staging.Add({className}.BlueprintId, new global::Fdp.Toolkit.Blueprints.BlueprintDefinition");
        WriteLine("{");
        Indent();
        WriteLine($"Name = \"{asset.Name}\",");
        WriteLine("Kind = global::Fdp.Toolkit.Blueprints.BlueprintDispatchKind.AiPrimitive,");
        WriteLine($"StructureHash = {className}.StructureHash,");
        WriteLine("StateSize = 0,");
        Outdent();
        WriteLine("});");

        // TODO (Phase 4): Register BTree thunks with BehaviorRegistry once the Interpreter
        // builder is in place.  The thunk methods (BTreeTick / BTreeEvaluate / HsmActivity /
        // HsmGuard) are emitted above and callable via reflection; runtime wiring happens
        // in HR-001 (AiHotReloadCoordinator).
    }

    private void EmitInstanceRegistration(string className, IrAsset asset)
    {
        var eventHandlers = asset.Graphs
            .Where(g => g.Kind == IrGraphKind.Event)
            .ToList();

        WriteLine($"staging.Add({className}.BlueprintId, new global::Fdp.Toolkit.Blueprints.BlueprintDefinition");
        WriteLine("{");
        Indent();
        WriteLine($"Name = \"{asset.Name}\",");
        WriteLine("Kind = global::Fdp.Toolkit.Blueprints.BlueprintDispatchKind.Instance,");
        WriteLine($"StructureHash = {className}.StructureHash,");
        WriteLine($"StateSize = {className}.StateSize,");
        WriteLine($"StateClrType = typeof({className}.State),");
        WriteLine($"InitDefault = {className}.InitDefault,");
        WriteLine($"Tick = {className}.TickThunk,");
        if (eventHandlers.Count > 0)
        {
            WriteLine("EventHandlers = new global::System.Collections.Generic.Dictionary<string, global::Fdp.Toolkit.Blueprints.EventHandlerDelegate>(global::System.StringComparer.Ordinal)");
            WriteLine("{");
            Indent();
            foreach (var evtGraph in eventHandlers)
                WriteLine($"[\"{evtGraph.Name}\"] = {className}.Event_{evtGraph.Name}_Thunk,");
            Outdent();
            WriteLine("},");
        }
        Outdent();
        WriteLine("});");
    }
}
