using System.Numerics;
using NodeEditor.Core.Interfaces;

namespace Hrot.UI.Common.AddEntity;

/// <summary>
/// ⭐ <c>CE-1017</c> S5 — the entity icon library: serves <c>entity/&lt;name&gt;</c> icon keys as textures, for the Add
/// Entity picker's rows and preview pane. 📄 docs/DESIGN_Add_Entity_Picker.md D3c, S5.
///
/// <para>⭐ Where an icon comes from, in order: <c>&lt;overrideDirectory&gt;/&lt;name&gt;.png</c> (so a TKB author adds art
/// without a rebuild — the <c>Assets/EntityIcons/</c> folder <c>IgVisualDef.IconName</c> names), then the PNGs embedded
/// in this assembly (<c>Assets/EntityIcons</c>, generated by <c>scripts/gen-entity-icons.py</c>). A name with no art
/// falls back to <c>_point</c>, so a TKB that names a missing icon still shows a marker, not a gap.</para>
///
/// <para>⭐ Every other key goes to <paramref name="fallback"/> — the host's existing provider (silk atlas: folder icons,
/// node icons) — so one provider serves a whole picker. Textures are uploaded lazily on first use (inside the ImGui
/// frame, where a GL context exists) and cached; a failed upload (texture id 0, a headless GL) is cached as "no icon".</para>
/// </summary>
public sealed class EntityIconLibrary : IIconProvider
{
    /// <summary>Key prefix this library serves.</summary>
    public const string Prefix = EntityTypeCatalog.IconKeyPrefix;
    /// <summary>Icon used for a name with no art.</summary>
    public const string MissingName = "_point";

    private readonly IIconProvider? _fallback;
    private readonly Func<string, byte[]?> _png;
    private readonly Func<byte[], (nint TextureId, int Width, int Height)?> _upload;
    private readonly Dictionary<string, IconHandle?> _cache = new(StringComparer.Ordinal);

    /// <summary>Creates the library.</summary>
    /// <param name="fallback">Serves every non-<c>entity/</c> key (the host's icon provider), or null.</param>
    /// <param name="overrideDirectory">A folder searched before the embedded art; null ⇒
    /// <c>&lt;app&gt;/Assets/EntityIcons</c>.</param>
    /// <param name="upload">Turns PNG bytes into a texture; null ⇒ raylib. Tests inject a fake.</param>
    public EntityIconLibrary(IIconProvider? fallback = null, string? overrideDirectory = null,
                             Func<byte[], (nint TextureId, int Width, int Height)?>? upload = null)
    {
        _fallback = fallback;
        string dir = overrideDirectory ?? Path.Combine(AppContext.BaseDirectory, "Assets", "EntityIcons");
        _png = name => ReadPng(dir, name);
        _upload = upload ?? RaylibUpload;
    }

    /// <summary>The icon names embedded in this assembly.</summary>
    public static IReadOnlyList<string> EmbeddedNames { get; } = typeof(EntityIconLibrary).Assembly
        .GetManifestResourceNames()
        .Where(n => n.StartsWith("EntityIcons/", StringComparison.Ordinal) && n.EndsWith(".png", StringComparison.Ordinal))
        .Select(n => n["EntityIcons/".Length..^".png".Length])
        .OrderBy(n => n, StringComparer.Ordinal)
        .ToArray();

    /// <inheritdoc/>
    public bool TryGet(string key, out IconHandle handle)
    {
        if (key is null || !key.StartsWith(Prefix, StringComparison.Ordinal))
        {
            if (_fallback is not null) return _fallback.TryGet(key!, out handle);
            handle = default;
            return false;
        }

        string name = key[Prefix.Length..];
        if (!_cache.TryGetValue(name, out var cached))
        {
            cached = Load(name) ?? (name == MissingName ? null : Load(MissingName));
            _cache[name] = cached;
        }
        handle = cached ?? default;
        return cached is not null;
    }

    private IconHandle? Load(string name)
    {
        var bytes = _png(name);
        if (bytes is null) return null;
        var tex = _upload(bytes);
        if (tex is not { } t || t.TextureId == 0) return null;
        return new IconHandle(t.TextureId, (uint)t.Width, (uint)t.Height, Vector2.Zero, Vector2.One);
    }

    private static byte[]? ReadPng(string dir, string name)
    {
        if (name.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0 || name.Contains("..")) return null;
        try
        {
            var path = Path.Combine(dir, name + ".png");
            if (File.Exists(path)) return File.ReadAllBytes(path);
        }
        catch (IOException) { }
        catch (UnauthorizedAccessException) { }

        using var s = typeof(EntityIconLibrary).Assembly.GetManifestResourceStream("EntityIcons/" + name + ".png");
        if (s is null) return null;
        using var ms = new MemoryStream();
        s.CopyTo(ms);
        return ms.ToArray();
    }

    private static (nint, int, int)? RaylibUpload(byte[] png)
    {
        var img = Raylib_cs.Raylib.LoadImageFromMemory(".png", png);
        if (img.Width == 0) return null;
        var tex = Raylib_cs.Raylib.LoadTextureFromImage(img);
        Raylib_cs.Raylib.UnloadImage(img);
        if (tex.Id == 0) return null;
        Raylib_cs.Raylib.SetTextureFilter(tex, Raylib_cs.TextureFilter.Bilinear);
        return ((nint)tex.Id, tex.Width, tex.Height);
    }
}
